### ISSUE TITLE
很神奇的现象

### ISSUE THREAD

**Issue by abings** [fluttercandies/extended_text_field#10]
我在阿里咸鱼的 fish_redux 页面里面使用 extended_text_field，如果录入内容有中文和表情的情况下，没录入一个表情，中文会上下跳动。。。。找不到原因，求大神解疑。

**Comment by abings** [comment]
所有布局结构和 demo原结构一样，直接搬到一个view里面，就出现这个情况。表情不会抖动，只是中文会整体上下抖动

**Comment by zmtzawqlp** [comment]
官方bug，你把右边的那个装饰去掉。。不久抖了

**Comment by abings** [comment]
@zmtzawqlp 谢谢回复，去掉装饰后依然抖动。  
有两种情况：
  一、  位置1 [表情图]       -》如果 同一行最后一个  是表情图，那么修改‘位置1’部分的普通文字，不会抖动
二、 [表情图]位置1   -》如果同一行最后一个不是表情图，那么在‘位置1’位置增删普通文章，整个录入框内普通文章都会抖动（表情不会抖动）

不知道如果把普通文字的设置为垂直对齐居中，会不会 抖动？ 请问能增加对齐设置吗，其实还是有这个对齐需求的。不一定都是底部对齐。

**Comment by abings** [comment]
跟了下代码，发现在render单元 的 void _paintContents(PaintingContext context, Offset offset)方法中不知道为什么_paintOffset 的 dy 会有可能变成 负值，如果在这里把负值修正为 0，抖动消失。

bug 现象是     文字1[代表表情图]文字2 中：  文字1 的光标 和 文字2的光标是不一样的高度。

**Comment by zmtzawqlp** [comment]
你试试最新的版本呢

**Comment by abings** [comment]
@zmtzawqlp 还是同样的问题。 表情图  前后文字的光标高度不一致，就一定会抖动。 导致_paintOffset 异常的负数等于 _updateVisibleRegionMinY 里产生的的那个 _visibleRegionMinY

**Comment by abings** [comment]
你这个版本更新后，  文字1[表情图]文字2   光标原来  在文字2三个字符任一位置的高度和文字1都不一样，现在是 只有在最后 和前面不一样了

**Comment by zmtzawqlp** [comment]
_visibleRegionMinY   只是计算选择小水滴的，跟文字花在哪个位置没有关系。。建议你提供能够重现问题的demo，以便调试

**Comment by zmtzawqlp** [comment]
你是ios上面的问题吗
