### ISSUE TITLE
当文本具有图像时，文本选择变得奇怪

### ISSUE THREAD

**Issue by LaelLuo** [fluttercandies/extended_text_field#103]
复现: 打开 `custom toolbar` demo, 在文本开头插入图片, 然后重复输入换行符, 直到图片超出可见范围为止, 然后随便输入一些文字, 尝试去选择这些文字, 视图会跳回开头.

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_field/issues/31
