### ISSUE TITLE
I can't find any example for inline images in examples

### ISSUE THREAD

**Issue by KarimMohamed20** [fluttercandies/extended_text_field#105]
Can anyone help me with example for images ?
<img width="300" alt="Screen Shot 2020-12-03 at 12 46 09 AM" src="https://user-images.githubusercontent.com/37942217/100940684-16482b80-3501-11eb-993e-790c6618c64d.png">

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_field/blob/8026bcb1a2c5628d4f68bc9934f665cf8de04399/example/lib/special_text/image_text.dart#L8
