### ISSUE TITLE
iOS模拟器使用，处于激活状态时，CPU功耗直线上升

### ISSUE THREAD

**Issue by Apparitionqk** [fluttercandies/extended_text_field#106]
iOS模拟器使用，处于激活状态时，CPU功耗直线上升，添加了TextEditingController，并注册了监听，focusNode.unfocus()之后，就没事儿了，这是缺少啥参数设置么

**Comment by zmtzawqlp** [comment]
何不用真机试试

**Comment by Apparitionqk** [comment]
> 何不用真机试试

AS对于iphone真机，息屏断连，也不能wifi连接，巨难受，而且iphone不能查数据库数据，模拟器可以省去很多麻烦

**Comment by zmtzawqlp** [comment]
模拟器说不清楚，毕竟用户不用模拟器，你可以用vscode试试

**Comment by Apparitionqk** [comment]
> 模拟器说不清楚，毕竟用户不用模拟器，你可以用vscode试试

那我去试试。
再请教大佬一个问题，flutter跑在iOS14的真机上，拔了数据线，App就启动不起来，官方说是解决了这个问题，可是我升级到1.22.4还是有这个问题，有碰到过么？

**Comment by zmtzawqlp** [comment]
是没办法debug，ios14
