### ISSUE TITLE
iOS长按粘贴操作后，继续长按，全选操作，就不在弹窗“复制、粘贴、剪切”工具条了 

### ISSUE THREAD

**Issue by Eddiegooo** [fluttercandies/extended_text_field#107]
iOS长按输入框，粘贴操作后。 在输入框文本后面继续长按，出现工具条，这时使用“全选”操作， 就不在继续弹窗“复制、粘贴、剪切”工具条了 。
Flutter SDK 1.22.4 
extend_text_field: ^5.0.2

**Comment by zmtzawqlp** [comment]
无法重现

**Comment by Eddiegooo** [comment]
> 无法重现

我这里必现的问题呢。  下载最新5.0.3源文件example工程也一样的。

在输入框双击，出现“粘贴、全选”工具条， 这时候选择“粘贴”。    然后在文末双击，出现“粘贴、全选”工具条，这时候选择“全选”， 就不会在出现快捷操作工具条。

再次双击，出现“粘贴、全选”工具条，这时候选择“全选”，就可以出现“剪切、拷贝、粘贴”工具条了。


就是只要粘贴完，在双击使用全选，就不会出现工具条。

**Comment by eronakoto** [comment]
Android设备也是如此，似乎只要用软键盘追加一个字符后就会恢复正常。

**Comment by zmtzawqlp** [comment]
官方的会吗

**Comment by eronakoto** [comment]
> 官方的会吗

我将extended_text_field 升级到了 5.0.3，此问题依旧是存在的。我也在调试检查代码可能出错的地方。
总结出来:
1、使用官方Demo 中的 （InsertText 或 ManualDelete） 函数往编辑器内追加删除字符会导致“全选”无法出现工具条
2、使用工具条 “全选” -> “粘贴” -> “长按末尾空白” -> "全选" 导致无法出现工具条

但，一旦使用系统软件盘向其追加内容后，就可以正常 "全选" 出现工具条了

**Comment by Eddiegooo** [comment]
> 官方的会吗

官方的Textfield 不会。

**Comment by eronakoto** [comment]
> 过一会尝试下5.0.4

经反复测试，已完美解决 [赞][赞][赞]

**Comment by Eddiegooo** [comment]
> 过一会尝试下5.0.4

使用5.0.4测试了一下，解决了。666
