### ISSUE TITLE
当text_field输入框可以滚动时，自定义的emoji定位错误

### ISSUE THREAD

**Issue by cixiu** [fluttercandies/extended_text_field#11]
当输入框的内容超过maxLines后内容区域可以滚动，自定义的emoji定位错误。
具体出现的场景如下gif图。

![text_field](https://user-images.githubusercontent.com/26104985/61881391-258c9180-af29-11e9-81a1-ae634a57e5c9.gif)

**Comment by zmtzawqlp** [comment]
使用版本，flutter版本告诉一下

**Comment by cixiu** [comment]
@zmtzawqlp 1.7.8+hotfix.3

**Comment by zmtzawqlp** [comment]
@cixiu 看看新版本是否解决

**Comment by cixiu** [comment]
@zmtzawqlp 感谢，新版已经解决了。
