### ISSUE TITLE
[SUGGESTION] Include the currently targeted flutter version (e.g. stable 1.22.6) in the README

### ISSUE THREAD

**Issue by jlund24** [fluttercandies/extended_text_field#114]
I've been using this package for a while now and love it! However, a frequent annoyance is being caught in limbo when there are updates to flutter because this package is so critical to our application I can't risk it not working. I've also noticed several other issues that appear here are usually due to confusion over which version of flutter to use. I've gathered from your comments that you target the stable channel, but many people trying to use the package don't know that.

So, my suggestion is to include a brief line or tag in the README that includes the currently targeted flutter version to reduce confusion and make it clear when we can update to newer versions. Thank you again for an incredible package and best of luck getting things up to date for the newest stable version.

**Comment by zmtzawqlp** [comment]
I will support non-null-safety and null-safety version later, thanks.
