### ISSUE TITLE
bug:系统输入法输入中文后，移动光标，点删除会闪退

### ISSUE THREAD

**Issue by markwu24** [fluttercandies/extended_text_field#122]
@zmtzawqlp 
1.最新7.0的版本，输入中文后，文字下面会有一条横线，sdk的textfield没有；
2.在输入中文后，需要删除中间的字，移动光标后，点删除，闪退，必现

https://user-images.githubusercontent.com/3362607/116362926-2c9aaf00-a835-11eb-9f83-d4b8f6f30789.MP4

**Comment by lijiankun24** [comment]
在 iOS 系统上，我这儿也有这两个问题，求官方解答
