### ISSUE TITLE
[Question] How can we highlight a regex match like a Url?

### ISSUE THREAD

**Issue by VictorUvarov** [fluttercandies/extended_text_field#123]
I would like to change the color of links. e.g. `https://www.google.com`

**Comment by antonygunawan94** [comment]
have you found a solution regarding this?

**Comment by VictorUvarov** [comment]
Yeah you can extend the text editing controller's `buildTextSpan` function. Here is a package that did something similar. https://github.com/micazi/rich_text_controller/blob/master/lib/rich_text_controller.dart

**Comment by antonygunawan94** [comment]
I see, but that need to extends the text editing controller,
is it possible to do it just based on this library?
thank you
