### ISSUE TITLE
[question] Is it possible to avoid rebuilding the widgets?

### ISSUE THREAD

**Issue by mordivgor** [fluttercandies/extended_text_field#124]
Hello,

I have noticed that tapping every letter makes that the whole text field is being rebuilt to check what widgets shall be placed inside it (kindly correct me if I am wrong). 
Unfortunately, downside of this way of working is that there is a visible blinking of widget/image spans (because they need to be build again).
Do you see any possibility to somehow avoid it?

**Comment by zmtzawqlp** [comment]
i have no idea , cursor should be painted every time
