### ISSUE TITLE
how to use onEnter

### ISSUE THREAD

**Issue by antonygunawan94** [fluttercandies/extended_text_field#126]
Hello, 

I'm trying to use `onEnter` inside `SpecialTextSpan` but it won't work
here is my snippet on how I used it
`
SpecialTextSpan(
      text: text,
      actualText: text,
      deleteAll: false,
      style: textStyle,
      start: start,
      onEnter: (event) {
        print("Entering mention");
      },
      onExit: (event) {
        print("Leaving mention");
      },
    )
`
are there anything wrong with my code?

Thank you

**Comment by zmtzawqlp** [comment]
It's only for extended_text
