### ISSUE TITLE
How to use regex?

### ISSUE THREAD

**Issue by antonygunawan94** [fluttercandies/extended_text_field#127]
Hello,

Is there a way to detect a regex such as URL Link?

Thank you

**Comment by zmtzawqlp** [comment]
how to convert text to textspan, it's base on yourself.

**Comment by antonygunawan94** [comment]
@zmtzawqlp any example on how to do it with this library?
because on the example folder I couldn't found anything regarding how to do regex match
and I've tried to do it like this inside child of `SpecialTextSpanBuilder`

`
if (flag[flag.length - 1] == " " ||
        flag[flag.length - 1] == "\n" ||
        index == data.length - 1) {

      if (urlRegex.hasMatch(linkMatcher)) {
      
        return _LinkText(
          startFlag: linkMatcher.substring(1, linkMatcher.length - 1),
          endFlag: linkMatcher[linkMatcher.length - 1],
          textStyle: textStyle,
          start: data.indexOf(linkMatcher),
        );
      }
      linkMatcher = "";
    }

    linkMatcher += flag[flag.length - 1];
`

**Comment by zmtzawqlp** [comment]
@AlexV525

**Comment by AlexV525** [comment]
https://github.com/openjmu/OpenJMU/blob/master/lib/model/special_text.dart
