### ISSUE TITLE
Cannot be used in a widget test to enter text

### ISSUE THREAD

**Issue by johnnypcc** [fluttercandies/extended_text_field#128]
`await tester.enterText(extendedTextfieldFinder, 'abc');`

The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
Iterable.single (dart:core/iterable.dart:498:25)
WidgetController.state (package:flutter_test/src/controller.dart:154:42)
WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1031:42)
WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1030:39)
TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
WidgetTester.showKeyboard (package:flutter_test/src/widget_tester.dart:1030:27)
WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1057:13)
WidgetTester.enterText.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1056:39)
TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
WidgetTester.enterText (package:flutter_test/src/widget_tester.dart:1056:27)

The `extendedTextfieldFinder` is a Finder for an extended text field. If I replace this with a regular TextField, the test works.

Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (2 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

pubspec:
extended_text_field: ^8.0.0

**Comment by zmtzawqlp** [comment]
test package is  for official widget

**Comment by burhanrashid52** [comment]
Is there any way we can we `enterText` for ExtentedTextField ?

**Comment by johnnypcc** [comment]
> test package is for official widget

It's for testing any widget.

**Comment by johnnypcc** [comment]
> Is there any way we can we `enterText` for ExtentedTextField ?

You can do it this way:
`
await tester.tap(yourFinderForExtendedTextField);
tester.testTextInput.enterText('123456789');
`

**Comment by burhanrashid52** [comment]
> > Is there any way we can we `enterText` for ExtentedTextField ?
> 
> You can do it this way: `await tester.tap(yourFinderForExtendedTextField); tester.testTextInput.enterText('123456789');`

Thanks this works. However, if I try to find one widget after `enterText()` it fails.
`expect(find.text('123456789'),findsOneWidgte);`

Also, `pumpAndSettle()` did not worked.

Seems like this is happening because the `ExtentedTextFiled` does not use `Text` widget?
