### ISSUE TITLE
Strange behaviour with arrow keys

### ISSUE THREAD

**Issue by Zarainia** [fluttercandies/extended_text_field#129]
On Windows, pressing an arrow key in the ExtendedTextField will usually switch focus to the next focusable widget in that direction instead of moving through the text in the textfield. This is contrary to the normal, expected behaviour of the regular TextField, and is annoying when editing the text. In a multi-line textfield, the up arrow and right arrow will sometimes (rarely) exhibit the normal behaviour. In a single-line textfield, the right arrow normally works correctly. 

Also, pressing <kbd>Ctrl</kbd> + <kbd>Arrow</kbd> correctly moves by one word, but then causes this error (which does not happen in the normal TextField): 

```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 109 pos 12: '_positions.length == 1'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:109:12)
#3      ScrollAction.isEnabled (package:flutter/src/widgets/scrollable.dart:1076:38)
#4      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:365:36)
#5      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:708:20)
#6      FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1678:43)
...
====================================================================================================
```

**Comment by Zarainia** [comment]
I will also add that this also happens without any special options like `specialTextSpanBuilder` set.

**Comment by Zarainia** [comment]
It seems that creating a `RawKeyboardListener` and returning `KeyEventResult.handled` in the `onKey` callback of the `focusNode` will prevent this from happening. I'm not sure what this shows, maybe there's a `onKey` set that's catching the arrow key inputs, but this is the way to solve it. Nevertheless, it's unexpected that this would be required, and the default behaviour doesn't make sense on desktop.

**Comment by zmtzawqlp** [comment]
breaking with https://github.com/flutter/flutter/issues/84086,  i can't merge code from flutter sdk any more. if official works, let us find what different from official and this package

**Comment by Zarainia** [comment]
It also seems that this is related to trying to focus things in the direction of the arrow keys. So, for instance, the left/right arrow problems only occur when there are focusable elements to the left/right of the textfield, and similarly for the up/down problems. And by adding a `FocusScope` around the `ExtendedTextField`, it works correctly. Maybe somewhere it's trying too hard to focus the next focusable element.

**Comment by zmtzawqlp** [comment]
try latest version

**Comment by Zarainia** [comment]
This seems to be fixed.
