### ISSUE TITLE
How do I detect a certain text while typing?

### ISSUE THREAD

**Issue by jezsung** [fluttercandies/extended_text_field#133]
I'd like to implement a mention feature similar to what the current major big social platforms like Facebook, Instagram do. Whenever a user type something starts with `@` , I want to listen that event and show possible mentionable users. Is it possible with this package?

**Comment by zmtzawqlp** [comment]
controller or ontextchange

**Comment by Krishnak561** [comment]
@jezsung, did manage to do that? 
@ mentions I mean.!
