### ISSUE TITLE
8.0.0出现了 Error: The non-abstract class 'ExtendedTextSelectionState' is missing implementations for these members:

### ISSUE THREAD

**Issue by liu1070832898** [fluttercandies/extended_text_field#134]
![image](https://user-images.githubusercontent.com/29189440/131310431-911ddf7e-eb94-4ab4-9a39-d1f4765d51aa.png)

**Comment by liu1070832898** [comment]
![image](https://user-images.githubusercontent.com/29189440/131310613-12c9c24d-5057-450f-82da-86947d5af448.png)

**Comment by zmtzawqlp** [comment]
找准，适配的版本
