### ISSUE TITLE
在桌面系统使用时遇到两个很影响使用体验的大问题

### ISSUE THREAD

**Issue by gzlock** [fluttercandies/extended_text_field#135]
1. 方向键左右控制Cursor位置时，光标无法跨域SpecialText
2. 使用Del键删除SpecialText时，会破坏SpecialText的文本而不会删除整个SpecialText(期望跟退格键一样可以完整删除SpecialText)

使用extended_text_field自带的Example可以复现这两个问题(第二个问题我用到了ImageSpan的`<img />`文本)。

两个问题都在这个录屏里了

https://streamable.com/fpmpor

**Comment by zmtzawqlp** [comment]
手机端会吗？

**Comment by gzlock** [comment]
> 手机端会吗？

手机自带的输入法没有方向键和Del键(手机的键盘是退格键)应该是没问题的
但是如果手机+蓝牙键盘(有方向键和退格键的话)，我觉得也是会有这个问题

**Comment by zmtzawqlp** [comment]
等官方支持

**Comment by gzlock** [comment]
> 等官方支持

官方确认了会出支持WidgetSpan的TextField么

**Comment by zmtzawqlp** [comment]
breaking with flutter/flutter#84086

**Comment by zmtzawqlp** [comment]
Del键 的效果不是删除一个。你可以用桌面原生看看，其他效果已支持

**Comment by gzlock** [comment]
> Del键 的效果不是删除一个。你可以用桌面原生看看，其他效果已支持

系统 Win 11 

Flutter 2.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 097d3313d8 (10 days ago) • 2022-02-18 19:33:08 -0600
Engine • revision a83ed0e5e3
Tools • Dart 2.16.1 • DevTools 2.9.2

extended_text_field 10.0.0

最新的系统，最新的flutter版本，最新的extended_text_field，实测依然存在这两个问题：
左右方向键无法令到光标跨域Span
光标在Span元素前一位时按下Del键也只能删除一个Span(\<img/> 按一下Del键变 img />)的第一个字符

我开了个example https://github.com/gzlock/extended_text_field

希望可以再次打开这个issue
