### ISSUE TITLE
似乎无法从ExtendedTextField中获取到已经生成的所有的SpecialText?

### ISSUE THREAD

**Issue by gzlock** [fluttercandies/extended_text_field#136]
翻了下文档都没有提到。
有从SepcialText中收集数据再汇总的需求。

**Comment by zmtzawqlp** [comment]
说需求

**Comment by gzlock** [comment]
> 说需求

需求就是汇总文本框中@到的用户的id，我的自定义数据格式是`<at user-id="xxxxxx">`

希望可以有一个`List<SpecialText> ExtendedTextField.children`之类的列表

我试过在SpanBuilder.createSpecialText中实现，效果不理想。

有个奇怪的问题是createSpecialText中会抛出错误userId这个集合未初始化

atUsers这个数组倒是可以正常使用，但是用数组形式收集呢会有重复收集的问题，文本框每变动一次就会全部SpecialText再添加到这个数组一次。

```dart
class MySpanBuilder extends SpecialTextSpanBuilder {
  final List<AtSpan> atUsers = [];
  final Set<String> userId = {};

  @override
  SpecialText? createSpecialText(String flag,
      {TextStyle? textStyle,
      SpecialTextGestureTapCallback? onTap,
      required int index}) {
    if (flag == '') return null;
    if (isStart(flag, AtSpan.flag)) {
      final at = AtSpan(start: index - (AtSpan.flag.length - 1));
      atUsers.add(at);
      userId.add(at.userId)
      return at;
    }
  }
}
```

**Comment by zmtzawqlp** [comment]
收集来做什么

**Comment by gzlock** [comment]
> 收集来做什么

主要是用来实现动态显示用户的昵称，用户的昵称可以自由修改的，所以不能把用户昵称写死在原始的文本数据里
例如`<at user-id="1"/> <at user-id="2"/> <at user-id="1"/>`
当用户提交回复时，app可以同时提交一个@到的用户的去重ID数组`[1,2]`给后端，当app读取这个文本数据时，同时返回@到的用户的精简数据

**Comment by zmtzawqlp** [comment]
没听懂。你去群里问吧。你看看 alex 的app 吧。里面修改昵称也是有的。

**Comment by gzlock** [comment]
> 没听懂。你去群里问吧。你看看 alex 的app 吧。里面修改昵称也是有的。

其实不用管什么需求啊，只是想从ExtendedTextField中获取到已经生成的SpecialText列表而已

**Comment by gzlock** [comment]
收集的时机错了，在SpecialTextSpanBuilder.createSpecialText里SpecialText.finshText还没有调用，所以获取到了null
