### ISSUE TITLE
能否支持自定义control+v事件处理

### ISSUE THREAD

**Issue by wc2411888** [fluttercandies/extended_text_field#139]
现在的输入框默认control+v是将剪贴板中的文字进行粘贴，但是现在我们有需求是自己自定义粘贴文件的功能，需要将默认的粘贴文字的功能给关闭，能否提供个方法关闭默认粘贴行为，实现自定义粘贴（ps：我们现在开发的是windows平台）

**Comment by zmtzawqlp** [comment]
自己fork 改
