### ISSUE TITLE
苹果和安卓手机光标显示不一致

### ISSUE THREAD

**Issue by abings** [fluttercandies/extended_text_field#14]
在iPhone 和 安卓上，两个光标的高度不一致，苹果上录入 无抖动，安卓上回会抖动
苹果手机光标截图：
![](https://raw.githubusercontent.com/abings/test/master/image/IMG_1302.jpg)
安卓手机光标截图
![](https://raw.githubusercontent.com/abings/test/master/image/IMG_1304.jpg)

**Comment by zmtzawqlp** [comment]
as design，官方就这样设计的，安卓会比ios 上下各小 2.0

**Comment by zmtzawqlp** [comment]
// TODO(garyq): This is no longer producing the highest-fidelity caret
  // heights for Android, especially when non-alphabetic languages
  // are involved. The current implementation overrides the height set
  // here with the full measured height of the text on Android which looks
  // superior (subjectively and in terms of fidelity) in _paintCaret. We
  // should rework this properly to once again match the platform. The constant
  // _kCaretHeightOffset scales poorly for small font sizes.
  //
  /// On iOS, the cursor is taller than the cursor on Android. The height
  /// of the cursor for iOS is approximate and obtained through an eyeball
  /// comparison.

**Comment by zmtzawqlp** [comment]
我先改成一致高度好了，我看了下安卓系统内部的光标
