### ISSUE TITLE
after updated to flutter 2.8.0, one backspace key would delete two Chinese chars

### ISSUE THREAD

**Issue by welde-x** [fluttercandies/extended_text_field#141]
After updated to flutter 2.8.0, I found that one click of backspace on soft keyboard would lead to deleting two Chinese chars in extended_text_field: ^9.0.0 while official TextField acted normally. I didn't remember this happened before, if not related flutter 2.8.0 :)

After tracing a little, my temp solution is to add onKeyEvent in focusNode as followed. If someone runs into same trouble, you can try this.

  **KeyEventResult onKey(FocusNode f, KeyEvent e) {
    return KeyEventResult.handled;
  }
_focusNode = FocusNode(onKeyEvent: onKey);**

And following is two delete key event handlings traceback. 

First time: 
TextEditingActionTarget.delete (text_editing_action_target.dart:336)
_DeleteTextAction.invoke (default_text_editing_actions.dart:92)
ActionDispatcher.invokeAction (actions.dart:571)
ShortcutManager.handleKeypress (shortcuts.dart:717)
_ShortcutsState._handleOnKey (shortcuts.dart:918)
**FocusManager._handleKeyMessage (focus_manager.dart:1593)**
KeyEventManager.handleRawKeyMessage (hardware_keyboard.dart:832)
BasicMessageChannel.setMessageHandler.<anonymous closure> (platform_channel.dart:77)
BasicMessageChannel.setMessageHandler.<anonymous closure> (platform_channel.dart:76)
_DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (binding.dart:389)
_DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (binding.dart:386)
_invoke2.<anonymous closure> (hooks.dart:189)
_rootRun (zone.dart:1428)
_CustomZone.run (zone.dart:1328)
_CustomZone.runGuarded (zone.dart:1236)
_invoke2 (hooks.dart:188)
_ChannelCallbackRecord.invoke (channel_buffers.dart:42)
_Channel.push (channel_buffers.dart:132)
ChannelBuffers.push (channel_buffers.dart:329)
PlatformDispatcher._dispatchPlatformMessage (platform_dispatcher.dart:544)
_dispatchPlatformMessage (hooks.dart:83)

Second time:
**ExtendedTextSelectionRenderObject._handleDelete (extended_text_selection_render_object.dart:890)**
ExtendedTextSelectionRenderObject._handleKeyEvent (extended_text_selection_render_object.dart:586)
RawKeyboard.handleRawKeyEvent (raw_keyboard.dart:678)
KeyEventManager.handleRawKeyMessage (hardware_keyboard.dart:818)
BasicMessageChannel.setMessageHandler.<anonymous closure> (platform_channel.dart:77)
BasicMessageChannel.setMessageHandler.<anonymous closure> (platform_channel.dart:76)
_DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (binding.dart:389)
_DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (binding.dart:386)
_invoke2.<anonymous closure> (hooks.dart:189)
_rootRun (zone.dart:1428)
_CustomZone.run (zone.dart:1328)
_CustomZone.runGuarded (zone.dart:1236)
_invoke2 (hooks.dart:188)
_ChannelCallbackRecord.invoke (channel_buffers.dart:42)
_Channel.push (channel_buffers.dart:132)
ChannelBuffers.push (channel_buffers.dart:329)
PlatformDispatcher._dispatchPlatformMessage (platform_dispatcher.dart:544)
_dispatchPlatformMessage (hooks.dart:83)

**Comment by zmtzawqlp** [comment]
please update to 9.0.1

**Comment by Dakrain** [comment]
The error still happend in 9.0.1

**Comment by zmtzawqlp** [comment]
> The error still happend in 9.0.1

？？

**Comment by welde-x** [comment]
I tried 9.0.1, error didnt happen here :)

**Comment by zmtzawqlp** [comment]
> The error still happend in 9.0.1

make sure you are use 9.0.1 version and library 8.0.0

**Comment by Dakrain** [comment]
I did clean and everything worked fine :D thanks. Anyway i got a question, I there a way I can know which SpecialTextspan is delete?

**Comment by zmtzawqlp** [comment]
> I did clean and everything worked fine :D thanks. Anyway i got a question, I there a way I can know which SpecialTextspan is delete?

open another issue, maybe you need to set deleteall = true
