### ISSUE TITLE
How do I detect when a SpecialTextSpan is delete? 

### ISSUE THREAD

**Issue by Dakrain** [fluttercandies/extended_text_field#142]
I'd like to implement a mention features like Facebook, or other Social platform. When adding a new SpecialTextSpan I add an userid to a list and when the user remove the SpecialTextSpan I want to listen to what and which text is deleted by the user so I would check and remove the userid as well.
Something like this:
`deleteCallback: (String value) { }`

**Comment by zmtzawqlp** [comment]
Controller onTextChanged
