### ISSUE TITLE
先输入英文再输入中文,英文会上下跳一下,同时中英文光标的高度也不一致

### ISSUE THREAD

**Issue by relax976** [fluttercandies/extended_text_field#144]
当有多张图片,连续删除的时候,光标会变成选择模式

![企业微信截图_20220106103931](https://user-images.githubusercontent.com/18508725/148319586-29ce869d-2527-457b-9d41-d68337acc214.png)

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_text_field/versions/12.0.0 同步过官方代码的，试试，依然有问题再打开
