### ISSUE TITLE
一输入@符号就报错

### ISSUE THREAD

**Issue by yya5119** [fluttercandies/extended_text_field#145]
您好，首先感谢您提供这么好的开源项目，现在在使用中遇到了问题，还望能帮忙解疑。
我并没有实现@的特殊字符方法
当我输入文本时，只要包含@符号就会报错
我当前使用环境 win10,dart:2.15.0 flutter:2.8.1
Another exception was thrown: A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this      
occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#49445(physicalKey:
PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null,  
timeStamp: 25:07:53.910427, synthesized)
然后删除键删除无效 能正常输入
再次感谢！！！

**Comment by chifandeyu** [comment]
这个是flutter引擎的bug. 长按左边的shift键输入@触发了底层的bughttps://github.com/flutter/flutter/issues/104169#issuecomment-1143222198

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_text_field/versions/12.0.0 同步过官方代码的，试试，依然有问题再打开. 你可以看看最近的 stable 官方是否已经修复
