### ISSUE TITLE
TextInputAction.send 设置后不起作用

### ISSUE THREAD

**Issue by dvzhou** [fluttercandies/extended_text_field#146]

**Comment by zmtzawqlp** [comment]
官方可以吗

**Comment by dvzhou** [comment]
下面是我的代码
ExtendedTextField(
      specialTextSpanBuilder: TextSpanBuilder(showAtBackground: true),
      onTap: onTap,
      onChanged: (v) {
        onChangedCallBack(v);
      },
      onSubmitted: StorageManager.sharedPreferences.getBool(kChatSendSetting) == true
          ? (v) {
              onSubmittedCallBack(v);
            }
          : null,
      decoration: InputDecoration(border: InputBorder.none, focusedBorder: InputBorder.none, enabledBorder: InputBorder.none, contentPadding: EdgeInsets.symmetric(horizontal: 10.0)),
      controller: textController,
      focusNode: focusNode,
      textInputAction:  TextInputAction.send,
      maxLines:  5,
      minLines: 1,
      style: TextStyle(fontSize: 16.0, textBaseline: TextBaseline.alphabetic),
    )

当我设置textInputAction为TextInputAction.send时，如果maxLines大于1，键盘上的回行按钮还是回行按钮，如果maxLines=1，键盘上的回行按钮就变成了发送按钮。

**Comment by dvzhou** [comment]
demo中也是这样

**Comment by chenjiangmin** [comment]
textInputAction: TextInputAction.send
设置成发送之后

换行就无法使用； 
有办法能解决这个问题吗？

**Comment by zmtzawqlp** [comment]
如果官方也这样，建议给官方开issue

**Comment by Dove900412** [comment]
textInputAction: TextInputAction.send,
华为手机上，TextField可以显示“发送”按钮，ExtendedTextField显示换行

**Comment by Dove900412** [comment]
< extended_text 10.0.1 (was 11.0.0) (11.0.0 available)
< extended_text_field 11.0.1 (was 12.0.0) (12.0.0 available)
< extended_text_library 10.0.0 (was 11.0.1) (11.0.1 available)
不是最新代码

**Comment by zmtzawqlp** [comment]
> < extended_text 10.0.1 (was 11.0.0) (11.0.0 available) < extended_text_field 11.0.1 (was 12.0.0) (12.0.0 available) < extended_text_library 10.0.0 (was 11.0.1) (11.0.1 available) 不是最新代码

请使用最新的。最新的是同步了官方代码的

**Comment by Dove900412** [comment]
好，我更新一下flutter sdk
