### ISSUE TITLE
@userName 取消光标后，再获取光标点击大部分空白区域无反应（@userName的后方y轴中间空白区域） ，只有偏y轴下方或上方区域获取光标

### ISSUE THREAD

**Issue by q819438477** [fluttercandies/extended_text_field#147]

**Comment by q819438477** [comment]
@userName TapGestureRecognizer点击区域是占父视图全宽的，并不是@userName 字的宽度

**Comment by mashixin** [comment]
去除@人员的点击属性recognizer即可，@人员后的空白区域也响应了@人员的点击事件，去除即可恢复输入框的响应。
如果需要@人员的点击，就在点击事件中加个通知恢复输入框的第一响应
return showAtBackground
        ? BackgroundTextSpan(
            background: Paint()..color = Colors.blue.withOpacity(0.15),
            text: atText,
            actualText: atText,
            start: start!,

            ///caret can move into special text
            deleteAll: true,
            style: textStyle,
            recognizer: (TapGestureRecognizer()
              ..onTap = () {
                if (onTap != null) {
                  onTap!(atText);
                }
              }))
        : SpecialTextSpan(
            text: atText,
            actualText: atText,
            start: start!,
            style: textStyle,
            recognizer: (TapGestureRecognizer()
              ..onTap = () {
                if (onTap != null) {
                  onTap!(atText);
                }
              }));
