### ISSUE TITLE
使用iOS自带键盘输入，当光标插在两个标记的字符中间，输入匹配到自定义的表情规则时，光标位置错误

### ISSUE THREAD

**Issue by LWFLBB** [fluttercandies/extended_text_field#148]
https://user-images.githubusercontent.com/16347796/150929070-56c1e595-1641-4765-8485-63c977700b08.MP4

作者你好，如视频所示，当使用系统键盘时出现的问题，目前使用版本为8.0.0

**Comment by zmtzawqlp** [comment]
please provide runnable simple demo

**Comment by LWFLBB** [comment]
你好，最新的demo，然后修改EmojiUitl中_emojiMap所存的key为带中文或者类似[:$]等，通过系统输入法输入即可复现

**Comment by LWFLBB** [comment]
> 请提供可运行的简单演示

你好，最新的demo，然后修改EmojiUitl中_emojiMap所存的key为中文或者类似[:$]等，通过系统输入法带输入即可复现

**Comment by zmtzawqlp** [comment]
理论上不应该让用户直接输入表情的，新的光标位置应该自己去计算才是。 组件不知道你的下一个操作是什么
