### ISSUE TITLE
Build failed on the flutter2.8.1

### ISSUE THREAD

**Issue by hexbo** [fluttercandies/extended_text_field#152]
flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_field-8.0.0/lib/src/extended_editable_text.dart:1175:7: Error: The non-abstract class 'ExtendedEditableTextState' is missing implementations for these members:
 - AutofillClient.autofill
 - TextSelectionDelegate.copySelection
 - TextSelectionDelegate.cutSelection
 - TextSelectionDelegate.pasteText
 - TextSelectionDelegate.selectAll
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedEditableTextState extends State<ExtendedEditableText>
      ^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by zmtzawqlp** [comment]
use 9.0.0
