### ISSUE TITLE
一个小建议，写在这里

### ISSUE THREAD

**Issue by lvsecoto** [fluttercandies/extended_text_field#155]
作者写的很多extended库都很强大，大大优化了原来的组件，又不破坏Flutter设计规范。

希望作者更进一步，给Flutter官方提Pull Request，把这些强化的功能合入到Flutter官方组件库里。

这样这些功能更好持续发展下去，不用每次更新了Flutter版本后，这些组件就用不了。

也大大减轻了了作者更新第三方组件库的压力。

（Issue 的标题不知道怎么写，文笔不好，有人帮帮忙吗）

**Comment by mdddj** [comment]
想多了 不可能合并的

**Comment by zmtzawqlp** [comment]
官方更注重的是通用性，之前pr 过。尊重官方的想法
