### ISSUE TITLE
demo something wrong

### ISSUE THREAD

**Issue by xSharkM** [fluttercandies/extended_text_field#156]
10.0.0 version demo something wrong, watch the video for details ，there is a problem with the cursor

https://user-images.githubusercontent.com/16934523/159862448-9bbf078a-9ef2-4573-87c7-96d040ff35bd.mp4

.

**Comment by zmtzawqlp** [comment]
"extended_text_field" from pub.dev, specifically version 12.0.0, which claims to have synchronized the official code. Please give it a try, and if you still encounter issues, feel free to reopen it.
