### ISSUE TITLE
 [feature]Support flutter version 2.12.0

### ISSUE THREAD

**Issue by HatsuneMikuV** [fluttercandies/extended_text_field#157]
[+1814 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:1224:7: Error: The non-abstract class 'ExtendedEditableTextState' is missing implementations for these members:
[        ]  - TextInputClient.insertTextPlaceholder
[        ]  - TextInputClient.removeTextPlaceholder
[        ] Try to either
[        ]  - provide an implementation,
[        ]  - inherit an implementation from a superclass or mixin,
[        ]  - mark the class as abstract, or
[        ]  - provide a 'noSuchMethod' implementation.
[        ] class ExtendedEditableTextState extends State<ExtendedEditableText>
[        ]       ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] ../../flutter/packages/flutter/lib/src/services/text_input.dart:1122:8: Context: 'TextInputClient.insertTextPlaceholder' is defined here.
[        ]   void insertTextPlaceholder(Size size) {}
[        ]        ^^^^^^^^^^^^^^^^^^^^^
[        ] ../../flutter/packages/flutter/lib/src/services/text_input.dart:1125:8: Context: 'TextInputClient.removeTextPlaceholder' is defined here.
[        ]   void removeTextPlaceholder() {}
[        ]        ^^^^^^^^^^^^^^^^^^^^^
[ +895 ms] lib/pages/flutter_home/flutter_home.dart:124:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]       WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
[        ]                      ^
[        ] lib/pages/flutter_home/flutter_home.dart:135:24: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]         WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
[        ]                        ^
[        ] lib/pages/flutter_home/flutter_home.dart:144:26: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]           WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
[        ]                          ^
[        ] lib/pages/flutter_home/flutter_home.dart:210:40: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
[        ]  - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
[        ]         final caches = PaintingBinding.instance?.imageCache;
[        ]                                        ^
[        ] lib/pages/flutter_home/flutter_home.dart:220:25: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
[        ]  - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
[        ]         PaintingBinding.instance?.handleMemoryPressure();
[        ]                         ^
[        ] lib/pages/flutter_home/flutter_home.dart:256:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]       WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
[        ]                      ^
[ +780 ms] ../../../.pub-cache/hosted/pub.dartlang.org/percent_indicator-4.0.0/lib/linear_percent_indicator.dart:162:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]     WidgetsBinding.instance?.addPostFrameCallback((_) {
[        ]                    ^
[  +43 ms] ../../../.pub-cache/hosted/pub.dartlang.org/focus_detector-2.0.1/lib/focus_detector.dart:54:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]     WidgetsBinding.instance?.addObserver(this);
[        ]                    ^
[   +1 ms] ../../../.pub-cache/hosted/pub.dartlang.org/focus_detector-2.0.1/lib/focus_detector.dart:162:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]     WidgetsBinding.instance?.removeObserver(this);
[        ]                    ^
[ +706 ms] ../../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/cached_network_image_provider.dart:109:29: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
[        ]  - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
[        ]       () => PaintingBinding.instance?.imageCache?.evict(key),
[        ]                             ^
[   +1 ms] ../../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/multi_image_stream_completer.dart:152:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]     SchedulerBinding.instance?.scheduleFrameCallback(_handleAppFrame);
[        ]                      ^
[   +9 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-6.0.2+1/lib/src/extended_image.dart:1000:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]     WidgetsBinding.instance!.removeObserver(this);
[        ]                    ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-6.0.2+1/lib/src/extended_image.dart:1029:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]     WidgetsBinding.instance!.addObserver(this);
[        ]                    ^
[   +1 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-6.0.2+1/lib/src/extended_image.dart:1211:26: Warning: Operand of null-aware operation '!' has type 'SemanticsBinding' which excludes null.
[        ]  - 'SemanticsBinding' is from 'package:flutter/src/semantics/binding.dart' ('../../flutter/packages/flutter/lib/src/semantics/binding.dart').
[        ]         SemanticsBinding.instance!.accessibilityFeatures.invertColors;
[        ]                          ^
[ +171 ms] lib/utilities/flutter_xlider.dart:444:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]     WidgetsBinding.instance!.addPostFrameCallback((_) {
[        ]                    ^
[ +437 ms] ../../../.pub-cache/hosted/pub.dartlang.org/story_view-0.13.2/lib/widgets/story_image.dart:49:25: Warning: Operand of null-aware operation '!' has type 'PaintingBinding' which excludes null.
[        ]  - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
[        ]         PaintingBinding.instance!.instantiateImageCodec(imageBytes).then(
[        ]                         ^
[   +5 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/extended_image_provider.dart:28:30: Warning: Operand of null-aware operation '!' has type 'PaintingBinding' which excludes null.
[        ]  - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
[        ]       return PaintingBinding.instance!.imageCache!;
[        ]                              ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/extended_image_provider.dart:28:40: Warning: Operand of null-aware operation '!' has type 'ImageCache' which excludes null.
[        ]  - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('../../flutter/packages/flutter/lib/src/painting/image_cache.dart').
[        ]       return PaintingBinding.instance!.imageCache!;
[        ]                                        ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/extended_image_provider.dart:97:39: Warning: Operand of null-aware operation '!' has type 'PaintingBinding' which excludes null.
[        ]  - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
[        ]       () => load(key, PaintingBinding.instance!.instantiateImageCodec),
[        ]                                       ^
[   +1 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/platform.dart:26:21: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
[        ]  - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
[        ]     PaintingBinding.instance?.imageCache?.clear();
[        ]                     ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/platform.dart:27:21: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
[        ]  - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
[        ]     PaintingBinding.instance?.imageCache?.clearLiveImages();
[        ]                     ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/platform.dart:40:28: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
[        ]  - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
[        ]     return PaintingBinding.instance?.imageCache;
[        ]                            ^
[ +449 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_library-9.0.0/lib/src/selection/extended_text_selection_overlay.dart:176:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]     if (SchedulerBinding.instance!.schedulerPhase ==
[        ]                          ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_library-9.0.0/lib/src/selection/extended_text_selection_overlay.dart:178:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]       SchedulerBinding.instance!.addPostFrameCallback(_markNeedsBuild);
[        ]                        ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_library-9.0.0/lib/src/selection/extended_text_selection_overlay.dart:230:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]     if (SchedulerBinding.instance!.schedulerPhase ==
[        ]                          ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_library-9.0.0/lib/src/selection/extended_text_selection_overlay.dart:232:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]       SchedulerBinding.instance!.addPostFrameCallback(_markNeedsBuild);
[        ]                        ^
[   +2 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_library-9.0.0/lib/src/selection/extended_text_selection_overlay.dart:451:40: Error: Member not found: 'fadeDuration'.
[        ]         duration: TextSelectionOverlay.fadeDuration, vsync: this);
[        ]                                        ^^^^^^^^^^^^
[   +1 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_library-9.0.0/lib/src/selection/extended_text_selection_overlay.dart:593:73: Error: Too many positional arguments: 2 allowed, but 4 found.
[        ] Try removing the extra positional arguments.
[        ]     final Offset handleAnchor = widget.selectionControls.getHandleAnchor(
[        ]                                                                         ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_library-9.0.0/lib/src/selection/extended_text_selection_overlay.dart:644:58: Error: Too many positional arguments: 4 allowed, but 6 found.
[        ] Try removing the extra positional arguments.
[        ]               child: widget.selectionControls.buildHandle(
[        ]                                                          ^
[   +6 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:1455:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]       SchedulerBinding.instance!.addPostFrameCallback((_) {
[        ]                        ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:1561:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]     WidgetsBinding.instance!.removeObserver(this);
[        ]                    ^
[   +3 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:2230:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]     SchedulerBinding.instance!.addPostFrameCallback((Duration _) {
[        ]                      ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:2286:24: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]         WidgetsBinding.instance!.window.viewInsets.bottom) {
[        ]                        ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:2287:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]       SchedulerBinding.instance!.addPostFrameCallback((Duration _) {
[        ]                        ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:2291:26: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]           WidgetsBinding.instance!.window.viewInsets.bottom) {
[        ]                          ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:2295:43: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]     _lastBottomViewInset = WidgetsBinding.instance!.window.viewInsets.bottom;
[        ]                                           ^
[   +1 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:2475:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]       WidgetsBinding.instance!.addObserver(this);
[        ]                      ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:2476:45: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]       _lastBottomViewInset = WidgetsBinding.instance!.window.viewInsets.bottom;
[        ]                                             ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:2486:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ]       WidgetsBinding.instance!.removeObserver(this);
[        ]                      ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:2499:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]       SchedulerBinding.instance!
[        ]                        ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:2524:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]       SchedulerBinding.instance!
[        ]                        ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.0/lib/src/extended_editable_text.dart:2540:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]       SchedulerBinding.instance!
[        ]                        ^
[  +68 ms] ../../../.pub-cache/hosted/pub.dartlang.org/flutter_slidable-1.2.0/lib/src/auto_close_behavior.dart:391:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]       SchedulerBinding.instance!.addPostFrameCallback((Duration _) {
[        ]                        ^
[  +13 ms] ../../../.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:126:28: Warning: Operand of null-aware operation '?.' has type 'RendererBinding' which excludes null.
[        ]  - 'RendererBinding' is from 'package:flutter/src/rendering/binding.dart' ('../../flutter/packages/flutter/lib/src/rendering/binding.dart').
[        ]     assert(RendererBinding.instance?.renderView != null);
[        ]                            ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:127:50: Warning: Operand of null-aware operation '!' has type 'RendererBinding' which excludes null.
[        ]  - 'RendererBinding' is from 'package:flutter/src/rendering/binding.dart' ('../../flutter/packages/flutter/lib/src/rendering/binding.dart').
[        ]     var clipRect = Offset.zero & RendererBinding.instance!.renderView.size;
[        ]                                                  ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:170:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]         SchedulerBinding.instance!.addPostFrameCallback((timeStamp) {
[        ]                          ^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:193:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').

**Comment by zmtzawqlp** [comment]
no plan to support it
