### ISSUE TITLE
[feature]Support flutter version 3.0.0

### ISSUE THREAD

**Issue by azhansy** [fluttercandies/extended_text_field#160]
../../../.pub-cache/hosted/pub.dartlang.org/extended_text_field-10.0.1/lib/src/extended_editable_text.dart:1224:7: Error: The non-abstract class 'ExtendedEditableTextState' is missing implementations for these members:
 - TextInputClient.insertTextPlaceholder
 - TextInputClient.removeTextPlaceholder
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedEditableTextState extends State<ExtendedEditableText>
      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1124:8: Context: 'TextInputClient.insertTextPlaceholder' is defined here.
  void insertTextPlaceholder(Size size) {}
       ^^^^^^^^^^^^^^^^^^^^^
../../flutter/flutter/packages/flutter/lib/src/services/text_input.dart:1127:8: Context: 'TextInputClient.removeTextPlaceholder' is defined here.
  void removeTextPlaceholder() {}
       ^^^^^^^^^^^^^^^^^^^^^

**Comment by zmtzawqlp** [comment]
done
