### ISSUE TITLE
多行文本中插入图片高度没有做处理

### ISSUE THREAD

**Issue by 1203556555** [fluttercandies/extended_text_field#162]
如下图，插入图片后，行高没有做对应变化，遮挡了上面几行的文字
![image](https://user-images.githubusercontent.com/18067025/169634946-4e55d1a6-bb28-4e52-be6d-2f68e60de139.png)

**Comment by zmtzawqlp** [comment]
demo,version

**Comment by 1203556555** [comment]
版本：10.1.0

示例代码
import 'package:extended_text_field/extended_text_field.dart';
import 'package:flutter/material.dart';

import 'extended_textfield/my_special_text_span_builder.dart';

class ExtendedTextFieldPage extends StatefulWidget {
  const ExtendedTextFieldPage({Key? key}) : super(key: key);

  @override
  _ExtendedTextFieldPageState createState() => _ExtendedTextFieldPageState();
}

class _ExtendedTextFieldPageState extends State<ExtendedTextFieldPage> {

  final TextEditingController _textEditingController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('富文本'),
        actions: [
          TextButton(
            onPressed: (){
              _textEditingController.value = _textEditingController.value.copyWith(
                  text: "<img src='https://user-images.githubusercontent.com/18067025/169634946-4e55d1a6-bb28-4e52-be6d-2f68e60de139.png' width='100' height='100'/>"
              );
            },
            child: const Text('插入照片', style: TextStyle(color: Colors.black),)
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: ExtendedTextField(
              controller: _textEditingController,
              specialTextSpanBuilder: MySpecialTextSpanBuilder(
                showAtBackground: true,
              ),
              maxLines: null,
            )
          )
        ],
      ),
    );
  }
}

以上代码基于你们提供的Example

**Comment by zmtzawqlp** [comment]
不能重现

**Comment by zmtzawqlp** [comment]
<img width="283" alt="截屏2022-05-21 下午1 47 06" src="https://user-images.githubusercontent.com/16477333/169637645-317edcb6-216e-4988-9243-0a792ba89281.png">

**Comment by 1203556555** [comment]
你试试将图片插入在第二行 @zmtzawqlp

**Comment by zmtzawqlp** [comment]
请提供 runnable demo

**Comment by zmtzawqlp** [comment]
<img width="291" alt="截屏2022-05-21 下午1 51 12" src="https://user-images.githubusercontent.com/16477333/169637774-9670be5d-2daf-43a7-b67e-2bf3f786491f.png">

**Comment by 1203556555** [comment]
找到问题了，是我没设置
strutStyle: const StrutStyle()😂
