### ISSUE TITLE
咨询：如何在软盘键外，让exit响应backspace？

### ISSUE THREAD

**Issue by hello-soon** [fluttercandies/extended_text_field#163]
请问大家是用什么方法实现这个能力的？

![image](https://user-images.githubusercontent.com/62131847/169737867-f9053650-3d87-449a-affd-bacebfb0669b.png)

**Comment by zmtzawqlp** [comment]
image 会直接删掉的。又不影响，好好看demo

**Comment by hello-soon** [comment]
跑了demo，感觉insertText，manualDelete，可以分装成util供大家使用
