### ISSUE TITLE
咨询，怎么监听@字符的删除

### ISSUE THREAD

**Issue by git-maven** [fluttercandies/extended_text_field#164]
1.需求是做一个@人的uid收集
加入@的时候可以实现，但是键盘退格删除@的模块后怎么知道是删除了这个@的特殊字符

2.还有@@这种情况是会把前一个@也当做特殊字符，这总情况怎么处理呢

**Comment by zmtzawqlp** [comment]
1. delete all 会自动删除整个特殊字符，你可以在这个 widgetspan dispose的时候知道 
2. 怎么处理是用户的事情(怎么把一个文本变成 textspan)，组件只是提供最基础的解析方式。
