### ISSUE TITLE
光标在特殊字符串前后的位置，按左右方向键，没有反应

### ISSUE THREAD

**Issue by chifandeyu** [fluttercandies/extended_text_field#165]
1.在正常的字符串按左右方向键，可以正常前后移动光标，但是遇到特殊字符串就移动不了。
2.焦点在编辑框内，按住Ctrl键，再按左右方向键，光标跳转的位置错乱。不是切换在每个单词的前面。

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_text_field/versions/12.0.0 同步过官方代码的，试试，依然有问题再打开
