### ISSUE TITLE
当有@字符的时候，把光标放在@字符前输入，光标的显示会有问题，自动跳了一个字符

### ISSUE THREAD

**Issue by git-maven** [fluttercandies/extended_text_field#167]
web Demo可以复现

**Comment by git-maven** [comment]
![image](https://user-images.githubusercontent.com/45022397/173507019-86e288e4-43ab-4156-8c53-657753aa7d30.png)

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_text_field/versions/12.0.0 同步过官方代码的，试试，依然有问题再打开
