### ISSUE TITLE
pad外接键盘不支持上下左右控制

### ISSUE THREAD

**Issue by cochn** [fluttercandies/extended_text_field#171]
pad外接键盘中文输入联想词不支持上下左右控制，而且点击键盘delete时，联想词不会同步更

https://user-images.githubusercontent.com/16076050/178196666-4915c374-6a8e-42a8-94b1-012040d32efa.mp4

新

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_text_field/versions/12.0.0 同步过官方代码的，试试，依然有问题再打开
