### ISSUE TITLE
输入图片后，再在图片前输入词汇，selection总会移到词汇第一个字之后

### ISSUE THREAD

**Issue by Huahua2021** [fluttercandies/extended_text_field#172]
<center class="half">
     <img src="https://user-images.githubusercontent.com/74231510/180180631-5ebc3ecc-3e57-4315-a494-8b41be22b02b.png" width="300"/><img src="https://user-images.githubusercontent.com/74231510/180180644-9bb5b41e-728e-4cc3-8781-be47b8cfcc08.png" width="300"/><img src="https://user-images.githubusercontent.com/74231510/180180659-54f487e6-6fc6-461c-9f44-4fda9c997038.png" width="300"/><img src="https://user-images.githubusercontent.com/74231510/180180670-486d4eb1-cb21-41bf-9823-b5284cda3b3d.png" width="300"/>
</center>

插入图片后，图片之前的文字无法按词汇输入，selection总会移到词汇第一个字之后，中英文都有这个问题。

图1：先输入两个字“这些”，此时selection在“些”后面。
图2：再插入图片（表情包），此时selection在图片后面。
图3：再把selection选到图片前，并准备输入键盘提供的推断“东西”。
图4：点击图3中键盘上的“东西”，selection出现在“东西”中间，而理想情况是“西”之后。

**Comment by Huahua2021** [comment]
https://user-images.githubusercontent.com/74231510/180182077-8373daee-c6a4-4e5f-a838-8e21ad8ddb66.mov

这是一个视频的例子

**Comment by zmtzawqlp** [comment]
跟联想有关系吗。如果不是点击联想，而且手动输入有这个问题吗

**Comment by Huahua2021** [comment]
> 

依然有这个问题，哪怕只输入一个字，光标也会自动挪到这个字儿前面，只要在图片前输入，就一直会有这个问题

**Comment by zmtzawqlp** [comment]
试下最新的 github 提交。如果没问题，我再发到pub上面

**Comment by Huahua2021** [comment]
> 试下最新的 github 提交。如果没问题，我再发到pub上面

已经没问题了，感谢！

**Comment by zmtzawqlp** [comment]
> > 试下最新的 github 提交。如果没问题，我再发到pub上面
> 
> 已经没问题了，感谢！

帮忙多测试下，没问题的话。我晚上发到pub上面
