### ISSUE TITLE
cursor position on MacOS

### ISSUE THREAD

**Issue by cuishijie1991** [fluttercandies/extended_text_field#175]
![截屏2022-08-11 上午10 50 38](https://user-images.githubusercontent.com/17976216/184057020-e0cee2dd-d603-4c80-956b-aba62c667321.png)

on MacOS, the cursor position is not after character but on the middle

**Comment by cuishijie1991** [comment]
extended_text_field: 10.1.0

**Comment by zmtzawqlp** [comment]
"extended_text_field" from pub.dev, specifically version 12.0.0, which claims to have synchronized the official code. Please give it a try, and if you still encounter issues, feel free to reopen it.
