### ISSUE TITLE
Doesn’t compile on Flutter 3.3.0 due to the selectable area changes to the API

### ISSUE THREAD

**Issue by NamanShergill** [fluttercandies/extended_text_field#177]

**Comment by zmtzawqlp** [comment]
i don't see any breaking change for this

**Comment by NamanShergill** [comment]
Right, my bad. I was temporarily on the master channel of flutter to test something and missed switching it back, so this is an upcoming breaking change.

I will reopen this issue when those changes are merged into beta/stable.
