### ISSUE TITLE
Some emoij do not display correctly for some characters.

### ISSUE THREAD

**Issue by ToanBarcelona1998** [fluttercandies/extended_text_field#178]
https://user-images.githubusercontent.com/77067868/195553258-41ccfb03-6d69-4ad3-bcc1-1e15a41e07cc.mov

**Comment by zmtzawqlp** [comment]
simple runnable demo with those emoij

**Comment by zmtzawqlp** [comment]
"extended_text_field" from pub.dev, specifically version 12.0.0, which claims to have synchronized the official code. Please give it a try, and if you still encounter issues, feel free to reopen it.
