### ISSUE TITLE
The cursor is messed up when using special texts

### ISSUE THREAD

**Issue by dancb10** [fluttercandies/extended_text_field#179]
Seems like the cursor is messed up when using special characters. 
So when you insert for example @ at the beginning of the text field it will start jumping before the @ character when typing letters after this character. This issue happens all the time when placed at the beginning of the text field It happens on your given example as well. 

Or when you add the @ sign at the middle of a word, all typed letters that are written after this special character will cause the cursor to jump in front of the word.
for example if you have in the text field: `awesome` and you add `awe@some`, whenever you type a letter after @, the cursor will jump in front of @. This case doesn't always happen, something is triggering this strange behaviour 

I'm not sure exactly where the problem is but seems to be happening

**Comment by dancb10** [comment]
Seems like other people are seeing strange issues with the cursor
https://github.com/fluttercandies/extended_text_field/issues/156

**Comment by dancb10** [comment]
Same here: https://github.com/fluttercandies/extended_text_field/issues/167

**Comment by xietian0908** [comment]
me too

**Comment by xietian0908** [comment]
[# 10.1.1](https://github.com/fluttercandies/extended_text_field/commit/71bebbc5aaff31d40af4baa416b871b779f39d4d)

**Comment by zmtzawqlp** [comment]
"extended_text_field" from pub.dev, specifically version 12.0.0, which claims to have synchronized the official code. Please give it a try, and if you still encounter issues, feel free to reopen it.
