### ISSUE TITLE
macos使用系统复制粘贴功能，第二次让TextField高亮时，右击鼠标没有弹出粘贴弹框

### ISSUE THREAD

**Issue by lnd1992** [fluttercandies/extended_text_field#181]
选中某个文字复制，点击 1.Simple => 2.widget span 再点击To的输入框，这时右击鼠标可以弹出粘贴的弹框，点击空白处使高亮消失，再次点击To的输入框，这时右击鼠标，不再弹出粘贴的弹框

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_text_field/versions/12.0.0 同步过官方代码的，试试，依然有问题再打开
