### ISSUE TITLE
The cpu usage is about 20% on macOS when the cursor is blinking

### ISSUE THREAD

**Issue by CyrilHu** [fluttercandies/extended_text_field#183]
The cpu usage is about 20% when the cursor is blinking, but the [TextField](https://api.flutter.dev/flutter/material/TextField-class.html) of the flutter library is normal in the same app.

extended_text_field: 10.1.0
extended_text_library: 9.1.0

 • Flutter version 3.3.9 on channel stable 
 • Engine revision 8f2221fbef
 • Dart version 2.18.5
 • DevTools version 2.15.0

CPU Apple M1
macOS 13.0.1
Xcode Version 14.1

**Comment by zmtzawqlp** [comment]
you test in macos app?

**Comment by CyrilHu** [comment]
> you test in macos app?

yes, it's a Mac OS  app

**Comment by zmtzawqlp** [comment]
"extended_text_field" from pub.dev, specifically version 12.0.0, which claims to have synchronized the official code. Please give it a try, and if you still encounter issues, feel free to reopen it.
