### ISSUE TITLE
TextInputAction.send TextInputType.multiline的问题

### ISSUE THREAD

**Issue by chenjiangmin** [fluttercandies/extended_text_field#185]
很多三方的键盘[例如搜狗]，  设置之后之后
键盘上面 换行键 和发送键都有了。
但是发送键能正确使用， 换行键点击之后就无法换行了。 是一个空格的效果。
有办法能兼容这两个类型一起都是用吗？

像微信 和QQ等聊天工具都可以 换行和发送一起使用。

Many third-party keyboards [such as Sogou], after setting
Both the line feed key and the send key are available on the keyboard.
However, the Send key can be used correctly. After clicking the Line Feed key, line feed cannot be performed. Is the effect of a space.
Is there a way to be compatible with both types?
Chat tools like WeChat and QQ can be used together with line breaking and sending.

**Comment by zmtzawqlp** [comment]
如果官方也有这个问题。建议给官方开issue

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_text_field/versions/12.0.0 同步过官方代码的，试试，依然有问题再打开
