### ISSUE TITLE
Can you please post a full example?

### ISSUE THREAD

**Issue by arualana** [fluttercandies/extended_text_field#186]
Please can someone post a full example with the EmailText WidgetSpan?

I can't understand how to use it.

Thank you very much, sorry for the trouble

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_field/blob/master/example/lib/special_text/at_text.dart

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_field/blob/master/example/lib/special_text/at_text.dart

**Comment by zmtzawqlp** [comment]
please run demo and read the readme, https://github.com/fluttercandies/extended_text_field/blob/master/example/lib/special_text/email_text.dart
