### ISSUE TITLE
RegExpSpecialTextSpanBuilder

### ISSUE THREAD

**Issue by funny-code-ddo** [fluttercandies/extended_text_field#187]
Is RegExpSpecialTextSpanBuilder and RegExpSpecialText has any examples

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text/blob/master/example/lib/pages/regexp_text_demo.dart


https://github.com/fluttercandies/extended_text/blob/master/example/lib/text/regexp_special_text_span_builder.dart
