### ISSUE TITLE
win10一个Exception

### ISSUE THREAD

**Issue by cuishijie1991** [fluttercandies/extended_text_field#188]
flutter 版本3.0.5, 运行平台系统 windows10 pro，插件版本10.1.0

Bad state: No element
#0      _GrowableList.first (dart:core-patch/growable_array.dart:343)
#1      ExtendedRenderEditable.getEndpointsForSelection (package:extended_text_field/src/extended_render_editable.dart:1521)
#2      ExtendedTextSelectionOverlay._updateSelectionOverlay (package:extended_text_library/src/selection/extended_text_selection_overlay.dart:182)
#3      ExtendedTextSelectionOverlay.update (package:extended_text_library/src/selection/extended_text_selection_overlay.dart:163)
#4      ExtendedEditableTextState._updateOrDisposeSelectionOverlayIfNeeded (package:extended_text_field/src/extended_editable_text.dart:2149)
#5      ExtendedEditableTextState._didChangeTextEditingValue (package:extended_text_field/src/extended_editable_text.dart:2491)
#6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:324)
#7      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:428)
#8      TextEditingController.value= (package:flutter/src/widgets/editable_text.dart:159)
#9      ExtendedEditableTextState._value= (package:extended_text_field/src/extended_editable_text.dart:1948)
#10     ExtendedEditableTextState._formatAndSetValue (package:extended_text_field/src/extended_editable_text.dart:2363)
#11     ExtendedEditableTextState.userUpdateTextEditingValue (package:extended_text_field/src/extended_editable_text.dart:2608)
#12     ExtendedTextSelectionRenderObject._setTextEditingValue (package:extended_text_library/src/render_object/extended_text_selection_render_object.dart:613)
#13     ExtendedTextSelectionRenderObject.setSelection (package:extended_text_library/src/render_object/extended_text_selection_render_object.dart:636)
#14     ExtendedTextSelectionRenderObject.selectPositionAt (package:extended_text_library/src/render_object/extended_text_selection_render_object.dart:229)
#15     ExtendedTextSelectionGestureDetectorBuilder.onDragSelectionUpdate (package:extended_text_library/src/selection/extended_text_selection.dart:333)
#16     _TextSelectionGestureDetectorState._handleDragUpdateThrottled (package:flutter/src/widgets/text_selection.dart:2002)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_text_field/versions/12.0.0 同步过官方代码的，试试，依然有问题再打开
