### ISSUE TITLE
complex实例中 从表情栏切换到输入栏时 输入框有跳动现象

### ISSUE THREAD

**Issue by jy6c9w08** [fluttercandies/extended_text_field#192]
### Platforms

dart

### Description

在complex实例中 从表情栏切换到输入栏时 输入框有跳动现象 
![Untitled ‑ Made with FlexClip](https://user-images.githubusercontent.com/54264085/218764936-323eba58-88f8-474a-8010-a005d599b20a.gif)

### Why

希望能像输入栏切表情栏那样 输入框不跳动  或许这不是这个插件负责的问题 但是想问问解决这个问题的思路 感谢大佬
![Untitled ‑ Made with FlexClip (2)](https://user-images.githubusercontent.com/54264085/218766301-0598446e-fea7-4b8c-bffb-8050c00ae087.gif)

**Comment by zmtzawqlp** [comment]
没看过来有抖呢。qq 里面不也是这样。系统先关闭，然后表情才出来

**Comment by jy6c9w08** [comment]
是的 qq里面系统键盘先关闭 然后表情栏弹起 这是从系统键盘切换表情栏时 有记录键盘的高度 不会发生跳动 但是在这个例子中   从表情栏切换到系统键盘时 表情栏高度变0 输入框会快速下降 然后系统键盘升起 又再次把输入框顶起 这就存在输入框一定程度的跳动 (参考第一张gif) 

qq 的从表情栏切换到系统输入法给我的 感觉是 表情栏没有完全下降 只是到系统键盘的高度 然后系统键盘升起 刚好"遮盖"住表情栏 (其实这个不是很难解决 我尝试过本地保存键盘的高度能实现类似的效果 但在一次测试中,ios中系统输入法中的emoji 键盘的高度会变高 也就是存在两个键盘高度 如果两个都本地保存 我觉得这不是一个优雅的实现方式)  

> 没看过来有抖呢。qq 里面不也是这样。系统先关闭，然后表情才出来

**Comment by zmtzawqlp** [comment]
所以说。高度这个东西。只能根据系统告诉你的来。不同键盘高度是不一样的。实际上。我看了很多原生的app，还有直接写死高度的。。只能说。能运行就行

**Comment by jy6c9w08** [comment]
好吧 我翻找了各种开源有类似页面的app 基本都是存在一定的跳动 有的连高度都没算 想简单优雅实现qq那种效果 估计只能原生或者魔改textfield了 
最后感谢 大佬提供的各种插件 解决了我很多的问题
