### ISSUE TITLE
[Feature request]  请问怎么做到类似B站投票的功能？

### ISSUE THREAD

**Issue by anhuiwangwei** [fluttercandies/extended_text_field#193]
### Platforms

Android, iOS

### Description

我需要实现B站这种图片和文本组合在一起的特殊文本，但是目前无法实现这样的。希望获得帮助。

### Why

![Screenshot_2023-02-15-10-38-28-306_tv danmaku bili](https://user-images.githubusercontent.com/16700847/218914606-37a694df-8c04-4653-8829-861b1048728a.jpg)

我尝试使用SpecialTextSpan来实现，SpecialTextSpan必须填写text来展示文本，在children添加WidgetSpan添加图片，但是这种方式只能是在文本后面添加图片；
我还尝试了使用TextSpan去实现，在children中使用ImageSpan+SpecialTextSpan的方式，ImageSpan和SpecalTextSpan使用一样的actualText，但是还是无法实现相应的效果，指针不在文本之后，显得很奇怪；
我尝试用ExtendedWidgetSpan实现，但是本质上是WidgetSpan，会换行，不能实现我想要的效果。
希望获得帮助，怎么样才能实现这种方式。

**Comment by zmtzawqlp** [comment]
只有一种办法。那做一个那个图片的 字体，这样就会当作文本。也不会有 widgetspan 换行的问题了

**Comment by zmtzawqlp** [comment]
SpecialTextSpan(text:"",children:<>{SpecialWidgetSpan,SpecialTextSpan}

**Comment by zmtzawqlp** [comment]
涉及到 光标。请必须使用 Special。 普通的。是没办法知道位置的

**Comment by anhuiwangwei** [comment]
> SpecialTextSpan(text:"",children:<>{SpecialWidgetSpan,SpecialTextSpan}

没有SpecialWidgetSpan这个小组件呀，只有ExtendedWidgetSpan。
我的代码是这样子的：
`
SpecialTextSpan(
      text: "",
      actualText: voteStr,
      start: start!,
      children: [
        ExtendedWidgetSpan(
          actualText: voteStr,
          child: Image.asset(
            "assets/icon/ic_vote.png",
            width: 18.w,
            height: 18.w,
          ),
        ),
        SpecialTextSpan(
          actualText: voteStr,
          text: voteStr.substring(2, voteStr.length - 2),
          style: textStyle),
        )
      ],
    )
`
但是光标位置是不对的。
![Screenshot_20230215_150819](https://user-images.githubusercontent.com/16700847/218956846-bc1c5b41-1bd6-4a0f-9200-bf18c07f4e0c.png)

**Comment by zmtzawqlp** [comment]
不对。是因为你没有指定。start。

**Comment by anhuiwangwei** [comment]
> 不对。是因为你没有指定。start。

额 这个要怎么设置start呢？我尝试了几次都不能成功。很抱歉，可能我比较菜。

**Comment by anhuiwangwei** [comment]
> 不对。是因为你没有指定。start。

使用SpecialTextSpan的话 光标是可以在文本内部移动的吧。我希望的是不能再内部移动，如果方便的话，可以提供一下例子吗？邮箱地址:278910593@qq.com.非常感谢

**Comment by zmtzawqlp** [comment]
好好看demo

**Comment by anhuiwangwei** [comment]
> 好好看demo

Demo非常简单，都是直接设置start!就完事了。
使用extended_text展示很容易，但是编辑就是不行。使用extended_text_field就不行。
SpecialTextSpan本质是文本，所以光标可以移动到内部，和ExtendedWidgetSpan不同。
ExtendedWidgetSpan是本质是Widget，所以光标是无法在其内部移动的。
B站的这种是既要像文本一样展示，但是又是Widget，可以整体删除，又不能像文本一样让光标在文本内部移动。就目前我能想到的都尝试了。

**Comment by zmtzawqlp** [comment]
``` dart
import 'package:extended_text_library/extended_text_library.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

class DollarText extends SpecialText {
  DollarText(TextStyle? textStyle, SpecialTextGestureTapCallback? onTap,
      {this.start})
      : super(flag, flag, textStyle, onTap: onTap);
  static const String flag = '\$';
  final int? start;
  @override
  InlineSpan finishText() {
    final String text = getContent();

    return SpecialTextSpan(
        text: '',
        actualText: '',
        start: start!,
        children: <InlineSpan>[
          ExtendedWidgetSpan(
            start: start!,
            actualText: '',
            child: Container(
              width: 10,
              height: 10,
              color: Colors.red,
            ),
          ),
          SpecialTextSpan(
            text: text,
            start: start!,
            actualText: toString(),
            deleteAll: true,
          ),
        ],

        ///caret can move into special text
        deleteAll: true,
        style: textStyle?.copyWith(color: Colors.orange),
        recognizer: TapGestureRecognizer()
          ..onTap = () {
            if (onTap != null) {
              onTap!(toString());
            }
          });
  }
}

List<String> dollarList = <String>[
  '\$Dota2\$',
  '\$Dota2 Ti9\$',
  '\$CN dota best dota\$',
  '\$Flutter\$',
  '\$CN dev best dev\$',
  '\$UWP\$',
  '\$Nevermore\$',
  '\$FlutterCandies\$',
  '\$ExtendedImage\$',
  '\$ExtendedText\$',
];

```

**Comment by anhuiwangwei** [comment]
> ```dart
> import 'package:extended_text_library/extended_text_library.dart';
> import 'package:flutter/gestures.dart';
> import 'package:flutter/material.dart';
> 
> class DollarText extends SpecialText {
>   DollarText(TextStyle? textStyle, SpecialTextGestureTapCallback? onTap,
>       {this.start})
>       : super(flag, flag, textStyle, onTap: onTap);
>   static const String flag = '\$';
>   final int? start;
>   @override
>   InlineSpan finishText() {
>     final String text = getContent();
> 
>     return SpecialTextSpan(
>         text: '',
>         actualText: '',
>         start: start!,
>         children: <InlineSpan>[
>           ExtendedWidgetSpan(
>             start: start!,
>             actualText: '',
>             child: Container(
>               width: 10,
>               height: 10,
>               color: Colors.red,
>             ),
>           ),
>           SpecialTextSpan(
>             text: text,
>             start: start!,
>             actualText: toString(),
>             deleteAll: true,
>           ),
>         ],
> 
>         ///caret can move into special text
>         deleteAll: true,
>         style: textStyle?.copyWith(color: Colors.orange),
>         recognizer: TapGestureRecognizer()
>           ..onTap = () {
>             if (onTap != null) {
>               onTap!(toString());
>             }
>           });
>   }
> }
> 
> List<String> dollarList = <String>[
>   '\$Dota2\$',
>   '\$Dota2 Ti9\$',
>   '\$CN dota best dota\$',
>   '\$Flutter\$',
>   '\$CN dev best dev\$',
>   '\$UWP\$',
>   '\$Nevermore\$',
>   '\$FlutterCandies\$',
>   '\$ExtendedImage\$',
>   '\$ExtendedText\$',
> ];
> ```

谢谢，看懂了。很感谢！

**Comment by anhuiwangwei** [comment]
谢谢，看懂了。很感谢！
