### ISSUE TITLE
Handling with composing text.

### ISSUE THREAD

**Issue by AlexVincent525** [fluttercandies/extended_text_field#2]
This is a specific case on the iOS platform, when user is typing or focused on the text field. The composing attribute will always be true and the composing will be `TextRange(start: 0, end: 0)` even if user is not typing with composed input method.
And of this will made the code in `buildTextSpan` failed in most of time on the iOS and some times on Android.
```
if (!widget.obscureText && _value.composing.isValid) { // The code won't leave here unless user tap the text field.
  final TextStyle composingStyle = widget.style.merge(
    const TextStyle(decoration: TextDecoration.underline),
  );
  return TextSpan(style: widget.style, children: <TextSpan>[
    TextSpan(text: _value.composing.textBefore(_value.text)),
    TextSpan(
      style: composingStyle,
      text: _value.composing.textInside(_value.text),
    ),
    TextSpan(text: _value.composing.textAfter(_value.text)),
  ]);
}
```

**Comment by zmtzawqlp** [comment]
fix with 2b3e3b01aefd9fa53f646a928d1ad6a99f317069
