### ISSUE TITLE
高亮匹配的问题

### ISSUE THREAD

**Issue by SeongBrave** [fluttercandies/extended_text_field#202]
### Content

作者您好，探讨一个问题：需要实现类似Discord或者飞书的功能，就是@输入所在频道中的人才会高亮，如果@了一个不存在的人不应该高亮，不确定是我用的不对还是什么呢，跑默认的demo啊，只要输入类似:"@张三 " 就会高亮了，存在@ 然后以空格" " 断开就高亮了，能否加一个业务逻辑吗？比如匹配了规则然后需要通过业务查询下，存在才高亮，不存在就不能高亮

**Comment by zmtzawqlp** [comment]
逻辑完成可以自己实现，SpecialTextSpanBuilder只是提供了常用的逻辑
