### ISSUE TITLE
[Discussions] widget.onAppPrivateCommand!(action, data);能否改成空安全调用

### ISSUE THREAD

**Issue by yangzai100** [fluttercandies/extended_text_field#203]
### Content

 @override
  void performPrivateCommand(String action, Map<String, dynamic> data) {
    widget.onAppPrivateCommand!(action, data);
  }
能否改成空安全调用widget.onAppPrivateCommand?(action, data);
我这边没有设置这个方法,但是用户不知道怎么触发了,我这边不想报错,也不想处理.

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_text_field/versions/12.0.0 同步过官方代码的，试试，依然有问题再打开
