### ISSUE TITLE
[Feature request] Is there an extended version of TextFormField 

### ISSUE THREAD

**Issue by LianYangCn** [fluttercandies/extended_text_field#206]
### Platforms

Android, iOS, macOS, Web, Windows, Linux

### Description

Seems there is no extended version of TextFormField.

### Why

I get a workaround, that put an invisible TextFormField beside an ExtendTextFiled to listen to the form event(like onSave or Validator), which is ugly. so, could you please?

**Comment by zmtzawqlp** [comment]
no plan to support
