### ISSUE TITLE
[Discussions] display `actualText` when cursor is near the `SpecialTextSpan`

### ISSUE THREAD

**Issue by invobzvr** [fluttercandies/extended_text_field#209]
### Content

For the example `DollarText`, suppose I input the string `aaa $bbb$ ccc $ddd$`, and it will display `aaa bbb ccc ddd`, where the substring `bbb` and `ddd` is in orange .
I wanna to display the `actualText` (`aaa $bbb$ ccc ddd`) when the cursor is near the `bbb`, at the edge of it or just inside it.
How to implement?
Thanks.

**Comment by zmtzawqlp** [comment]
addListener to selection  and  show a overlay

**Comment by invobzvr** [comment]
> addListener to selection and show a overlay

Thanks for quick response.
It seems I can't update the input freely that case.
Is it able to be implemented more natively? like a markdown real-time render?
