### ISSUE TITLE
Weird behaviour on pressing 'Enter' in an extended_text_field 

### ISSUE THREAD

**Issue by aasaanapps** [fluttercandies/extended_text_field#21]
On pressing 'Enter' to insert a newline character to the text, the '\n' is inserted to text but the cursor does not move to the next line. It stays on the same line and moves one character back, which was kind of weird. Can you please look into the issue?

The example used is - TextSelectionControls

**Comment by zmtzawqlp** [comment]
does it happen in official TextField, it's better to provide a runable demo for this

**Comment by aasaanapps** [comment]
I am using the example provided in the repo. PFA the code I am running as a flutter project.
In example 1 & 3, if you press 'Enter', the cursor does not move to the next line.
In example 2, at first the cursor moves to the next line when pressing enter, but after inserting an emoji it behaves similar to example 1&3.

[issue_text_field.zip](https://github.com/fluttercandies/extended_text_field/files/3544344/issue_text_field.zip)

**Comment by aasaanapps** [comment]
The official TextField is working fine. Please find the source code of official text field example below.

[simple_text_field.zip](https://github.com/fluttercandies/extended_text_field/files/3544389/simple_text_field.zip)

**Comment by zmtzawqlp** [comment]
this is refer to https://github.com/flutter/flutter/issues/35869
try to do selection with widgetspan, but _textPainter.getOffsetForCaret return Offset.zero when textspan has widgetspans, could you please report to flutter team about it?

getOffsetForCaret  is not right for widgetspan, so i use getBoxesForSelection but it seems that it's not good for "\n"

**Comment by zmtzawqlp** [comment]
https://github.com/flutter/flutter/issues/38474  wait for flutter team to add support

**Comment by aasaanapps** [comment]
Thanks for the quick reply :) will surely wait for them to add support.

**Comment by zmtzawqlp** [comment]
i have do a workaround about this issue in  extended_text_library, please run packages get, make sure extended_text_library is 0.4.9 version. please tell me if it works.

**Comment by aasaanapps** [comment]
Nope it is still failing. I updated extended_text_library and tried it for Example 1. custom toolbar.
When I types a few words in the last line and pressed 'Enter' the cursor strangely moved back by 2 characters instead of going to the next line.

```
  extended_text_library:
    dependency: "direct main"
    description:
      name: extended_text_library
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.9"

```

**Comment by zmtzawqlp** [comment]
I could't reproduce, which flutter sdk do you use? i'm in 1.9.5

**Comment by aasaanapps** [comment]
I am using the stable version v1.7.8+hotfix.4.

**Comment by zmtzawqlp** [comment]
gif to reproduce it, will helpful if you have a time

**Comment by aasaanapps** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.37.1)
[!] Connected device
    ! No devices available

**Comment by aasaanapps** [comment]
sure I will make a gif.

**Comment by aasaanapps** [comment]
Might be some issue with caching .. I closed everything .. opened the project again .. did a pub get again .. and ran the project .. the issue is no longer there (weird!). 

Thanks for the fix. Cheers!

**Comment by zmtzawqlp** [comment]
I'm glad to solve it with workaround for now, let us await for official  fixing of widgetspan
