### ISSUE TITLE
macos 左右按键获取光标位置不正确

### ISSUE THREAD

**Issue by sevenkkk** [fluttercandies/extended_text_field#210]
### Content

添加表情之后，用左右键移动光标，获取的光标位置不正确。
运行官方的例子就有这个问题。

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_text_field/versions/12.0.0 同步过官方代码的，试试，依然有问题再打开

**Comment by sevenkkk** [comment]
我更新了最新代码， 运行demo但是还是有这个问题：
flutter 版本:3.10.4
我录制了视频：
https://github.com/fluttercandies/extended_text_field/assets/74165239/5f418f1e-a129-441b-b66e-0f953ffdc7f7

**Comment by zmtzawqlp** [comment]
12.0.1 is ready on pub, reopen if it still has problem.

**Comment by miti-mio** [comment]
extended_text_field也有这个问题
