### ISSUE TITLE
[Discussions] multi match using `RegExpSpecialTextSpanBuilder`

### ISSUE THREAD

**Issue by invobzvr** [fluttercandies/extended_text_field#211]
### Content

Suppose I have the following rules:
- `$(.+)$` for orange color
- `*(.+)*` for bold style

and the input string `$aaa$ *$bbb$ ccc*`.
Currently I got `aaa $bbb$ ccc`, since `buildWithRegExp` only match once, so `bbb` is bold but NOT in orange.
I wanna make `bbb` is both bold and in orange.
How to implement?
Thanks.

**Comment by zmtzawqlp** [comment]
SpecialTextSpanBuilder just simple demo，you can implement it base on your case.
