### ISSUE TITLE
package is not compatible with Dart 3 & Flutter 3.10 

### ISSUE THREAD

**Issue by siddharthadevops** [fluttercandies/extended_text_field#212]
### Version

extended_text_field: ^11.0.1

### Platforms

dart

### Device Model

all

### flutter info

```sh
-
```

### How to reproduce?

Is there any timeline to solve this problem?

### Logs

```sh
-
```

**Comment by zmtzawqlp** [comment]
package is refactoring

**Comment by junko2013** [comment]
Error (Xcode): ../../.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-11.0.1/lib/src/extended_render_editable.dart:82:40: Error: Type 'BidirectionalIterator' not found

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_text_field/versions/12.0.0-dev is publish.

**Comment by junko2013** [comment]
收到。。
