### ISSUE TITLE
[Bug report] 单纯@某人的时候 点击输入框无法弹出键盘

### ISSUE THREAD

**Issue by mnock** [fluttercandies/extended_text_field#214]
### Version

12.0.0 

### Platforms

Android, iOS

### Device Model

iphone X

### flutter info

```sh
Flutter (Channel stable, 3.10.2, on macOS 12.5 21G72 darwin-x64, locale zh-Hans-CN)
```

### How to reproduce?

https://github.com/fluttercandies/extended_text_field/assets/16587910/8586c868-d159-416e-9f3e-75c5c2083da2

**Comment by zmtzawqlp** [comment]
那是因为光标已经在输入框里面了，请按照自己的逻辑修改

**Comment by mnock** [comment]
> 那是因为光标已经在输入框里面了，请按照自己的逻辑修改。example 只是例子。

之前版本是好的 就是单纯只有@的情况下 才会这样。@某人 后面加个表情或者文字就不会有这个问题呢

**Comment by zmtzawqlp** [comment]
> > 那是因为光标已经在输入框里面了，请按照自己的逻辑修改。example 只是例子。
> 
> 之前版本是好的 就是单纯只有@的情况下 才会这样。@某人 后面加个表情或者文字就不会有这个问题呢

之前没有 同步官方的代码，一切都以官方行为为准
