### ISSUE TITLE
[Bug report]  error in flutter 3.13.0 `Error: Type 'CaretChangedHandler' not found.`

### ISSUE THREAD

**Issue by mdddj** [fluttercandies/extended_text_field#221]
### Version

12.0.1

### Platforms

dart

### Device Model

all

### flutter info

```sh
3.13.0
```

### How to reproduce?

构建失败

### Logs

```sh
Could not build the precompiled application for the device.
Error (Xcode): ../.pub-cache/hosted/pub.dev/extended_text_field-12.0.1/lib/src/official/rendering/editable.dart:493:3: Error: Type 'CaretChangedHandler' not found.
```

**Comment by sharokh1** [comment]
Same

**Comment by 1284115201** [comment]
Same issue

**Comment by tianlang8279** [comment]
Same issue

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_field/commit/358c55e6dacdb2c9336f5b9379ad892e4aa01fc4

**Comment by tianlang8279** [comment]
just found out

**Comment by tianlang8279** [comment]
> 

just found out

**Comment by tianlang8279** [comment]
> 12.1.0 is ready
> 
> [358c55e](https://github.com/fluttercandies/extended_text_field/commit/358c55e6dacdb2c9336f5b9379ad892e4aa01fc4)

just found out
