### ISSUE TITLE
TextInputType.text 时，IOS设备 默认是英文键盘，并且无法切换成拼音输入法

### ISSUE THREAD

**Issue by githubZpp** [fluttercandies/extended_text_field#223]
### Platforms

iOS

### Description

extended_text_field: ^10.0.1

TextInputType.text 时，IOS设备 默认是英文键盘，并且无法切换成拼音输入法

### My code

ExtendedTextField(
              decoration: const InputDecoration(
                  border: InputBorder.none,
                  contentPadding:
                      EdgeInsets.symmetric(horizontal: 10, vertical: 10),
                  isCollapsed: true),
              controller: C_.textEditingController,
              cursorColor: Color(0xffEC35FF),
              strutStyle: StrutStyle(),
              focusNode: C_.focusNode,
              textInputAction: TextInputAction.next,
              minLines: 1,
              maxLines: 2,
              onEditingComplete: () {
                C_.addStickerToText("\n");
              },
              keyboardType: TextInputType.text,
              onChanged: (val) {
                C_.messageText = val;
                if (val.isEmpty) {
                  C_.state.hiddenSendBtn();
                } else {
                  C_.state.showSendBtn();
                }
              },
              specialTextSpanBuilder:
                  MyWXSpecialTextSpanBuilder(showAtBackground: true),
            ),

### Try do it

GetMaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          fontFamily: "PingFang",
        ),
        translations: Messages(),
        initialRoute: AppRoute.LUNCH,
        getPages: AppPages.routes,
        builder: initDialog(),
        locale: Locale('zh', 'CH'),
        supportedLocales: [const Locale('zh', 'CH')],
      ),

----&
info.plist

<key>CFBundleLocalizations</key>
	<array>
		<string>zh</string>
		<string>en</string>
	</array>
	<key>CFBundleDevelopmentRegion</key>
	<string>zh_CN</string>

**Comment by zmtzawqlp** [comment]
这种问题先找官方证实
