### ISSUE TITLE
[Bug report] 自动换行时，不能滚动完全显示新的一行

### ISSUE THREAD

**Issue by wpfchina** [fluttercandies/extended_text_field#226]
### Version

12.1.0

### Platforms

iOS

### Device Model

ios模拟器， iphone 14

### flutter info

```sh
Flutter 3.13.0
```

### How to reproduce?

使用官方master的demo。
文字大小14，高1.5
图片大小30.
ExtendedTextField默认1行，最大3行。

操作：
不断插入图片，
自动换行时，不能滚动完全显示新的一行。
导致新插入的图片不能完全显示。

从表现看看，滚动显示新一行，好像跟行高有关，文字大小14 x 高1.5 = 21

### Example code (optional)

```Dart
官方demo，
修改example/lib/pages/simple/widget_span.dart
ExtendedTextField默认1行，最大3行，
```

**Comment by wpfchina** [comment]
https://github.com/fluttercandies/extended_text_field/assets/90514329/ae87b0df-193e-45e6-9339-2c3a3b8a2d07

**Comment by Evenjine** [comment]
> Simulator.Screen.Recording.-.iPhone.14.Pro.-.2023-09-18.at.16.44.50.mp4

It seems like Flutter 3.13.6 no longer has this issue.

**Comment by azhansy** [comment]
> > Simulator.Screen.Recording.-.iPhone.14.Pro.-.2023-09-18.at.16.44.50.mp4
> 
> It seems like Flutter 3.13.6 no longer has this issue.
My flutter version is 3.13.8 and I still have this problem

**Comment by azhansy** [comment]
> > Simulator.Screen.Recording.-.iPhone.14.Pro.-.2023-09-18.at.16.44.50.mp4
> 
> It seems like Flutter 3.13.6 no longer has this issue.

My flutter version is 3.13.8 and I still have this problem.

**Comment by zmtzawqlp** [comment]
try the latest version or 12.1.1
