### ISSUE TITLE
[Discussions] copy SpecialTextSpan

### ISSUE THREAD

**Issue by HuangZiquan** [fluttercandies/extended_text_field#227]
### Content

SpecialTextSpan有什么方式可以自行决定复制的文字吗？

假设文字是`@account `，显示的时候会替换成`@Mike `。
如果我使用滑鼠选取并复制`@Mike `，实际上复制的文字是`@account `，预期的结果是要复制`@Mike `才对。

**Comment by zmtzawqlp** [comment]
那建议从源头就把字符串替换掉
