### ISSUE TITLE
[Discussions] Flutter 3.16.0

### ISSUE THREAD

**Issue by ChanNagihong** [fluttercandies/extended_text_field#229]
### Content

Error compiling with Flutter 3.16.0

**Comment by ChanNagihong** [comment]
../../../.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-12.1.0/lib/src/official/widgets/text_selection.dart:2716:56: Error: The getter 'keysPressedOnDown' isn't defined for the class 'TapDragEndDetails'.
 - 'TapDragEndDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../Development/flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'keysPressedOnDown'.
    final bool isShiftPressed = _containsShift(details.keysPressedOnDown);
    
../../../.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-12.1.0/lib/src/official/widgets/editable_text.dart:4761:62: Error: The argument type 'double' can't be assigned to the parameter type 'TextScaler'.
 - 'TextScaler' is from 'package:flutter/src/painting/text_scaler.dart' ('../../../Development/flutter/packages/flutter/lib/src/painting/text_scaler.dart').
                WidgetSpan.extractFromInlineSpan(inlineSpan, textScaleFactor));

**Comment by moweiran** [comment]
https://github.com/fluttercandies/extended_text_field/pull/230

**Comment by lizhichuan** [comment]
+1

**Comment by zmtzawqlp** [comment]
Migrate to Flutter 3.16.0
