### ISSUE TITLE
android build 版本和 ios build 版本layoutInlineChildren传入参数不一致

### ISSUE THREAD

**Issue by Sailingee** [fluttercandies/extended_text_field#242]
### Version

flutter3.19 extended_text_field:13.1.0

### Platforms

Android

### Device Model

apix sdk 29

### flutter info

```sh
extend_text_field-13.1.0/lib/src/official/rending/editable.dart layoutInlineChildren函数报错，只传入了两个参数，但android版本需要三个参数。ios版本正常。
```

### How to reproduce?

在mac androidstudio使用代码后，提交给git 然后使用windows使用该分支打包apk 报错

**Comment by zmtzawqlp** [comment]
自己检查， lock文件里面的版本是否一致

**Comment by azhansy** [comment]
Flutter 3.24.0 • channel stable • git@github.com:flutter/flutter.git
Framework • revision 80c2e84975 (8 days ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2

<img width="1338" alt="image" src="https://github.com/user-attachments/assets/49582e42-f770-4c44-b561-e579c0f33849">

**Comment by azhansy** [comment]
Flutter 3.24.0 • channel stable • git@github.com:flutter/flutter.git
Framework • revision 80c2e84975 (8 days ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2

<img width="1295" alt="image" src="https://github.com/user-attachments/assets/c8084dcd-daf6-4a30-93ba-57d9dda3bd57">

**Comment by zmtzawqlp** [comment]
close wtih https://github.com/fluttercandies/extended_text_field/commit/c298596a5648b2a610cfb42eb74595dcfed7eb5d
