### ISSUE TITLE
[Bug report] 当输入自定义格式，把光标移动到到自定义格式之前，然后输入拼音文本，确认后光标位置就不对了，这时候点击删除键，删除的文本就不对了，自定义格式就破坏了

### ISSUE THREAD

**Issue by GodCai** [fluttercandies/extended_text_field#255]
### Version

16.0.1

### Platforms

Windows

### Device Model

windows11

### flutter info

```sh
• Flutter version 3.24.5 on channel stable at E:\flutter\flutter_3.24.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (5 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

### How to reproduce?

当输入自定义格式例如我是图片，把光标移动到到自定义格式之前（不论是用鼠标，还是用键盘左键），然后输入拼音文本，确认后光标位置就不对了，这时候点击删除键，删除的文本就不对了，自定义格式就破坏了，总结应该是内部光标的位置，算法不对。
下面是我的demo
[editdemo.zip](https://github.com/user-attachments/files/18173673/editdemo.zip)

**Comment by GodCai** [comment]
官方demo也可以复现：先随便输入俩中文，然后插入$，然后把光标移动到$之前，在输入拼音，这时候光标位置就不对了，再点删除，$的格式就坏了，基本上判断为，显示文本和实际文本不一致时，会出现的bug

**Comment by zmtzawqlp** [comment]
[Uploading QQ20241218-214111.zip…]()
重现不了

**Comment by zmtzawqlp** [comment]
Uploading 无标题视频——使用Clipchamp制作.mp4…

你的demo 也重现不了

**Comment by zmtzawqlp** [comment]
https://github.com/user-attachments/assets/6ac0431f-5dee-41bb-a6ca-c3107b5f1bcc

**Comment by zmtzawqlp** [comment]
[QQ20241218-214111.zip](https://github.com/user-attachments/files/18183607/QQ20241218-214111.zip)

**Comment by zmtzawqlp** [comment]
你拉一下 github 最新代码，windows 上面如果没有问题，我再发布
