### ISSUE TITLE
BUG - method finishText on SpecialText class trim the last character and not the hole flag

### ISSUE THREAD

**Issue by rtmzshw** [fluttercandies/extended_text_field#27]
I was trying to use a flag that contains more than one character, and I found that this method trims only the last character. IDK why, but this function code is not available to debug or see.

way to reproduce - 
in the example switch the flag in dollar_text.dart to "_!" and in custom_toolbar.dart use this text as an example "join _!FlutterCandies_! something something" 
you will see that the end result is "join FlutterCandies_ something something".
expected result - "join FlutterCandies something something".
thank you for your time, great job with this library btw.

**Comment by zmtzawqlp** [comment]
please provide a runable demo, i will check it when i have a time.

“I was trying to use a flag that contains more than one character”
span has actual text and show text, for this case, you can take a look at
 https://github.com/fluttercandies/extended_text_field/blob/master/example/lib/special_text/image_text.dart

by the time , it's just  demo to show how to convert text to textspan, you should define your rule as your case.

**Comment by rtmzshw** [comment]
ok I get it, I override the SpecialTextSpanBuilder to fit for my case and it worked. thank you
