### ISSUE TITLE
hinttext and text not at a same horizontal line

### ISSUE THREAD

**Issue by NotSeriousCoder** [fluttercandies/extended_text_field#32]
你好，我发现输入框的hinttext 和 用户输入的文本不在同一条水平线上，并且我没有找到有参数可以设置hinttext的位置

图片如下：
http://yanxuan.nosdn.127.net/85f0d74c6961fa15b5b92d1147638469.png

**Comment by zmtzawqlp** [comment]
https://juejin.im/post/5d8d5a105188256ec311fa99#heading-41

![image](https://user-images.githubusercontent.com/16477333/69143702-907b5d00-0b04-11ea-9eab-5e3c124ce2b3.png)

**Comment by NotSeriousCoder** [comment]
> https://juejin.im/post/5d8d5a105188256ec311fa99#heading-41
> 
> ![image](https://user-images.githubusercontent.com/16477333/69143702-907b5d00-0b04-11ea-9eab-5e3c124ce2b3.png)

好的，非常感谢，我去试一下
