### ISSUE TITLE
快速删除字符后滚动位置不对

### ISSUE THREAD

**Issue by coolbluesky** [fluttercandies/extended_text_field#33]
在demo中设置输入框的最大行数3，输入超过最大行数的文字和表情，然后连续点删除，删除过程中滚动位置不对，光标不可见

![9vmx0-6ti8w](https://user-images.githubusercontent.com/8018493/69784298-6dca0200-11f0-11ea-8c66-b9d420fa3a07.gif)

**Comment by zhao0** [comment]
遇到同样问题

**Comment by zmtzawqlp** [comment]
fix in [0.4.8]
