### ISSUE TITLE
IOS编译出错

### ISSUE THREAD

**Issue by guoheping113** [fluttercandies/extended_text_field#34]
/Users/apple/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-0.4.4/lib/src/extended_editable_text.dart:700:7: Error:
    The non-abstract class 'ExtendedEditableTextState' is missing implementations for these members:
     - TextInputClient.connectionClosed
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.

    class ExtendedEditableTextState extends State<ExtendedEditableText>
          ^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../flutter/packages/flutter/lib/src/services/text_input.dart:661:8: Context: 'TextInputClient.connectionClosed' is
    defined here.
      void connectionClosed();
           ^^^^^^^^^^^^^^^^

**Comment by zmtzawqlp** [comment]
别用master
