### ISSUE TITLE
关于通过代码删除输入框内容

### ISSUE THREAD

**Issue by NotSeriousCoder** [fluttercandies/extended_text_field#35]
你好，不好意思又来打扰。我遇到这么一个问题，当输入框有类似 @xxx 的时候，我点击软键盘的回退键，它会被作为一个整体删除，但是如果我想通过代码实现它，我该怎么做呢？
其实我知道我可以仿照特殊文本的判断逻辑去识别它们，从而做到整体删除，但是觉得这样似乎太笨，理论上软键盘回退的逻辑，我应该可以同样调用才对。
我看了下，其实是通过调用ExtendedEditableTextState里面实现的TextInputClient接口的updateEditingValue实现的，但是我好像也没法获取到ExtendedEditableTextState的对象，因此也就无法调用它

另外说下为什么需要自己去做删除，因为Emoji键盘需要一个删除键，所以。。。

麻烦大神给指点一下，该怎么实现，谢谢！

**Comment by sayatokido** [comment]
我也遇到一样的问题

**Comment by zmtzawqlp** [comment]
里面的代码比较复杂。我空了看看能暴露出来不

**Comment by zmtzawqlp** [comment]
Add demo that how to delete text with code
