### ISSUE TITLE
Flutter 编译版本v1.9.1+hotfix.2 时，编译报错

### ISSUE THREAD

**Issue by Tinaltt** [fluttercandies/extended_text_field#45]
TextInputConnection 的 connectionClosedReceived()，估计官方删掉了，所以编译报错了，作者大大，可能得升级一下flutter啦~
还有这个方法应该替换成什么？否则编译报错！

`
Compiler message:
../../../../Library/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-0.4.6/lib/src/extended_editable_text.dart:1663:28: Error: The method 'connectionClosedReceived' isn't defined for the class 'TextInputConnection'.
 - 'TextInputConnection' is from 'package:flutter/src/services/text_input.dart' ('../../../../Library/flutter/packages/flutter/lib/src/services/text_input.dart').
Try correcting the name to the name of an existing method, or defining a method named 'connectionClosedReceived'.
      _textInputConnection.connectionClosedReceived();
                           ^^^^^^^^^^^^^^^^^^^^^^^^
Compiler failed on /Users/baomeng/opt/workspace/flutter/pikaBroadcaster/lib/main.dart

FAILURE: Build failed with an exception.
`

**Comment by zmtzawqlp** [comment]
使用0.4.4版本。别加箭头
