### ISSUE TITLE
Not Showing text while entering text from keyboard

### ISSUE THREAD

**Issue by gssinghgautam** [fluttercandies/extended_text_field#46]
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  _Editable-[GlobalKey#67361] file:///Users/kunwar/Documents/flutter/extended_text_field/lib/src/extended_editable_text.dart:1552:20
When the exception was thrown, this was the stack: 
#2      new TextPosition (dart:ui/text.dart:1372:15)
#3      ExtendedRenderEditable._updateSelectionExtentsVisibility (package:extended_text_field/src/extended_render_editable.dart:283:7)
#4      ExtendedRenderEditable._paintContents (package:extended_text_field/src/extended_render_editable.dart:1871:7)
#5      ExtendedRenderEditable.paint (package:extended_text_field/src/extended_render_editable.dart:1930:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
...
The following RenderObject was being processed when the exception was fired: ExtendedRenderEditable#5c1eb relayoutBoundary=up15
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=342.0, 0.0<=h<=Infinity)
...  size: Size(342.0, 19.0)
...  cursorColor: Color(0xff2196f3)
...  showCursor: ValueNotifier<bool>#a39a3(true)
...  maxLines: null
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 1, extentOffset: 1, affinity: null, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#25b08(offset: 0.0, range: 0.0..0.0, viewport: 19.0, ScrollableState, BouncingScrollPhysics, IdleScrollActivity#c7609, ScrollDirection.idle)
RenderObject: ExtendedRenderEditable#5c1eb relayoutBoundary=up15
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=342.0, 0.0<=h<=Infinity)
  size: Size(342.0, 19.0)
  cursorColor: Color(0xff2196f3)
  showCursor: ValueNotifier<bool>#a39a3(true)
  maxLines: null
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 1, extentOffset: 1, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#25b08(offset: 0.0, range: 0.0..0.0, viewport: 19.0, ScrollableState, BouncingScrollPhysics, IdleScrollActivity#c7609, ScrollDirection.idle)
...  text: TextSpan
...    debugLabel: (englishLike subhead 2014).merge(blackCupertino subhead)
...    inherit: false
...    color: Color(0xdd000000)
...    family: .SF UI Text
...    size: 16.0
...    weight: 400
...    baseline: alphabetic
...    decoration: TextDecoration.none
...    : TextSpan
...      debugLabel: (englishLike subhead 2014).merge(blackCupertino subhead)
...      inherit: false
...      color: Color(0xdd000000)
...      family: .SF UI Text
...      size: 16.0
...      weight: 400
...      baseline: alphabetic
...      decoration: TextDecoration.none
...      "@"
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by gliese667c** [comment]
相同问题。更新 flutter 到 stable 最新，extended_text_field  0.4.6
