### ISSUE TITLE
输入框显示bug

### ISSUE THREAD

**Issue by JackZhang1994** [fluttercandies/extended_text_field#47]
flutter版本：v1.12.13+hotfixes.6
extended_text_field版本：0.4.6
设备系统：Android 9.0
设备类型：一加5

当进行输入操作时，输入框的光标会消失，也无法看到之前输入的内容。运行example也是一样的结果

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_field/issues/46
