### ISSUE TITLE
iOS上点击某个文字编辑区域光标不能移动到指定位置，需要双击

### ISSUE THREAD

**Issue by ShinyG** [fluttercandies/extended_text_field#52]

**Comment by zmtzawqlp** [comment]
有图片是吗？

**Comment by ShinyG** [comment]
是

**Comment by zmtzawqlp** [comment]
你看看那个pinned的issue。没办法暂时，官方坑 https://github.com/fluttercandies/extended_text_field/issues/31

**Comment by ShinyG** [comment]
好的

**Comment by pengxueshan** [comment]
输入框内没有图片，只有纯文字，无法点击移动光标位置

**Comment by zmtzawqlp** [comment]
> 输入框内没有图片，只有纯文字，无法点击移动光标位置

你看ios默认行为吧

**Comment by pengxueshan** [comment]
发现修改extended_text_library库的extended_text_selection_render_object的selectWordEdge方法，可以解决问题，把111行由原来的：
onSelectionChanged != null
改成
onSelectionChanged == null

**Comment by zmtzawqlp** [comment]
> 发现修改extended_text_library库的extended_text_selection_render_object的selectWordEdge方法，可以解决问题，把111行由原来的：
> onSelectionChanged != null
> 改成
> onSelectionChanged == null

。。。。这个ios的标准行为。。。。

**Comment by pengxueshan** [comment]
大哥看能否修改release一个版本？

**Comment by zmtzawqlp** [comment]
> 大哥看能否修改release一个版本？

说了啊。。ios的默认行为啊。你要改就fork 过去。。github 引用呗

**Comment by pengxueshan** [comment]
OK。谢谢了

**Comment by zmtzawqlp** [comment]
> OK。谢谢了

谢谢反馈。问题已经修复

**Comment by gaoyong06** [comment]
> > OK。谢谢了
> 
> 谢谢反馈。问题已经修复

extended_text_field 0.5.0
ios 还是有这个问题.

看时间你们修改的时候extended_text_library 版本号是 0.5.4 吧
我只是在项目里面配置了 extended_text_field 0.5.0
是还需要更改别的什么地方嘛？

**Comment by zmtzawqlp** [comment]
> > > OK。谢谢了
> > 
> > 
> > 谢谢反馈。问题已经修复
> 
> extended_text_field 0.5.0
> ios 还是有“iOS上点击某个文字编辑区域光标不能移动到指定位置，需要双击”这个问题.
> 
> 看时间你们修改的时候extended_text_library 版本号是 0.5.4 吧
> 我只是在项目里面配置了 extended_text_field 0.5.0
> 是还需要更改别的什么地方嘛？

有箭头应该会自动获取最新的extended_text_library ，你可以自己看看.package确定下自己的版本
