### ISSUE TITLE
IOS点击backspace后会出现光标位置不正确的情况

### ISSUE THREAD

**Issue by daibao520** [fluttercandies/extended_text_field#59]
如图
![image](https://user-images.githubusercontent.com/6234955/76212633-e0ad3500-6243-11ea-89b2-2e80054e6598.png)
重现方法，输入一长串字符然后按点击backspace有几率会出现这种情况
ios手机上会这样，安卓不会

我的使用方式，像这样
`ExtendedTextField(          
                minLines: 1,
                maxLines: 5,
              ),`

**Comment by daibao520** [comment]
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale zh-CN)

**Comment by zmtzawqlp** [comment]
没有重现你图中的现象
