### ISSUE TITLE
长按选择不能默认选中全部文字

### ISSUE THREAD

**Issue by oyh819** [fluttercandies/extended_text_field#62]
1.长按的时候不能默认选中全部文字吗？现在发现只有数字的时候才是会选中全部文字，中文只会选中其中的一个文字。
2.长按的时候必须松手才会弹出选择框
3.如果文本用一个气泡包裹，有没有办法在长按气泡的时候就弹出选择框，并选中全部文字

**Comment by zmtzawqlp** [comment]
跟官方行为一样，你想全选。可以自己写代码
