### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method TextInput.setEditableSizeAndTransform on channel flutter/textinput))

### ISSUE THREAD

**Issue by zinwalin** [fluttercandies/extended_text_field#63]
extended_text_field  version 0.5.0

![image](https://user-images.githubusercontent.com/5416196/78870145-432e6680-7a78-11ea-8c54-836fed0b7c79.png)

**Comment by zmtzawqlp** [comment]
flutter version

**Comment by zinwalin** [comment]
> flutter version

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en)

**Comment by zmtzawqlp** [comment]
i can't reproduce it at my side, please give more info

**Comment by zinwalin** [comment]
> i can't reproduce it at my side, please give more info

![image](https://user-images.githubusercontent.com/5416196/79090793-65c4c600-7d7d-11ea-8367-65bf39a13246.png)

**Comment by zmtzawqlp** [comment]
reopen if the latest version still has problem.
