### ISSUE TITLE
请问一个实际使用中存在的问题

### ISSUE THREAD

**Issue by gaoyong06** [fluttercandies/extended_text_field#65]
例如我这些现在需求是，@用户 的格式是 @[Mention:987734,王老师]
(前面的987734 是用户的uid)

实际上输入框里面的内容是：

@[Mention:987734,王老师] 早上好

但是用户看输入框的时候里面是

**@王老师** 早上好

这样，所以涉及到一个文字模式， 和显示样式 替换的工作
这个 使用 extended_text_field应该如何实现呢？

**Comment by zmtzawqlp** [comment]
实际文字=@[Mention:987734,王老师]， 显示文本不是你自己返回的TextSpan吗
