### ISSUE TITLE
iOS上输入多行文字时，双击段落弹起的toolbar选项上不显示左右框选控制条

### ISSUE THREAD

**Issue by ShinyG** [fluttercandies/extended_text_field#66]
多行文字时：
![image](https://user-images.githubusercontent.com/17675303/81533955-b853cb00-9399-11ea-9847-e4b32b62d952.png)

单行文字时显示正常：
![image](https://user-images.githubusercontent.com/17675303/81534039-e0dbc500-9399-11ea-99e6-c0c0e23edf11.png)

**Comment by zmtzawqlp** [comment]
1.17？？ 我没做。你自己从1.17的代码里面copy出来吧

**Comment by zmtzawqlp** [comment]
哦？ 必现？ 感觉是官方计算的问题
