### ISSUE TITLE
ExtendedWidgetSpan: how do you change its style when tapping on it?

### ISSUE THREAD

**Issue by johngithubby** [fluttercandies/extended_text_field#75]
Hi! Having a ExtendedWidgetSpan, how do you change the above ExtendedWidgetSpan's style here after tapping it? Like text color and background?

```
ExtendedWidgetSpan(
      child: GestureDetector(
        child: ...
        ),
        onTap: () {
         //how do you change the above ExtendedWidgetSpan's style here? Like text color and background?
        },
      ),
      deleteAll: true,
    );
```

And how do I make the cursor disappear after the tap? I'd like this to look like the span was selected.
Thank you

Edit: after tapping a span and changing its style, I'd like to be able to delete it when the user presses backspace on the keyboard.

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_field/blob/master/example/lib/pages/widget_span.dart

**Comment by johngithubby** [comment]
@zmtzawqlp thanks but I'm already using the code in that example, it doesn't do what I was talking about.

**Comment by zmtzawqlp** [comment]
setstate after tap, you can pass callback into it

 the cursor disappear
FocusNode.unfocus()

**Comment by johngithubby** [comment]
And what should I do in the setState callback? Change the style of ExtendedTextField? But it may contain many ExtendedWidgetSpan widgets, how do I change only the ExtendedWidgetSpan that was tapped?

Also, I can’t I unfocus to make the cursor disappear, I need to have focus so that the user can tap backspace on the keyboard to delete the tapped ExtendedWidgetSpan

**Comment by zmtzawqlp** [comment]
pass context and FocusNode into SpecialTextSpanBuilder

**Comment by johngithubby** [comment]
I/m not sure I understand, can you please give more details? Thanks

**Comment by johngithubby** [comment]
So how can I change the style of ExtendedTextField using the context and FocusNode?
