### ISSUE TITLE
Can't run library demo. Compile error

### ISSUE THREAD

**Issue by xal** [fluttercandies/extended_text_field#79]
Can't run demo with next compile errors:

> Launching lib/main.dart on Android SDK built for x86 in debug mode...
> Running Gradle task 'assembleDebug'...
> 
> Compiler message:
> ../lib/src/extended_editable_text.dart:759:7: Error: The non-abstract class 'ExtendedEditableTextState' is missing implementations for these members:
>  - TextInputClient.currentAutofillScope
>  - TextInputClient.showAutocorrectionPromptRect
> Try to either
>  - provide an implementation,
>  - inherit an implementation from a superclass or mixin,
>  - mark the class as abstract, or
>  - provide a 'noSuchMethod' implementation.
> 
> class ExtendedEditableTextState extends State<ExtendedEditableText>
>       ^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../Apps/flutter/packages/flutter/lib/src/services/text_input.dart:769:21: Context: 'TextInputClient.currentAutofillScope' is defined here.
>   AutofillScope get currentAutofillScope;
>                     ^^^^^^^^^^^^^^^^^^^^
> ../../../../Apps/flutter/packages/flutter/lib/src/services/text_input.dart:784:8: Context: 'TextInputClient.showAutocorrectionPromptRect' is defined here.
>   void showAutocorrectionPromptRect(int start, int end);
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-3.0.0/lib/src/selection/cupertino_text_selection_controls.dart:295:10: Error: The method 'ExtendedCupertinoTextSelectionControls.buildToolbar' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildToolbar'.
>   Widget buildToolbar(
>          ^
> ../../../../Apps/flutter/packages/flutter/lib/src/widgets/text_selection.dart:134:10: Context: This is the overridden method ('buildToolbar').
>   Widget buildToolbar(
>          ^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-3.0.0/lib/src/selection/material_text_selection_controls.dart:628:10: Error: The method 'ExtendedMaterialTextSelectionControls.buildToolbar' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildToolbar'.
>   Widget buildToolbar(
>          ^
> ../../../../Apps/flutter/packages/flutter/lib/src/widgets/text_selection.dart:134:10: Context: This is the overridden method ('buildToolbar').
>   Widget buildToolbar(
>          ^
> 
> Compiler message:
> ../lib/src/extended_editable_text.dart:759:7: Error: The non-abstract class 'ExtendedEditableTextState' is missing implementations for these members:
>  - TextInputClient.currentAutofillScope
>  - TextInputClient.showAutocorrectionPromptRect
> Try to either
>  - provide an implementation,
>  - inherit an implementation from a superclass or mixin,
>  - mark the class as abstract, or
>  - provide a 'noSuchMethod' implementation.
> 
> class ExtendedEditableTextState extends State<ExtendedEditableText>
>       ^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../Apps/flutter/packages/flutter/lib/src/services/text_input.dart:769:21: Context: 'TextInputClient.currentAutofillScope' is defined here.
>   AutofillScope get currentAutofillScope;
>                     ^^^^^^^^^^^^^^^^^^^^
> ../../../../Apps/flutter/packages/flutter/lib/src/services/text_input.dart:784:8: Context: 'TextInputClient.showAutocorrectionPromptRect' is defined here.
>   void showAutocorrectionPromptRect(int start, int end);
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-3.0.0/lib/src/selection/cupertino_text_selection_controls.dart:295:10: Error: The method 'ExtendedCupertinoTextSelectionControls.buildToolbar' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildToolbar'.
>   Widget buildToolbar(
>          ^
> ../../../../Apps/flutter/packages/flutter/lib/src/widgets/text_selection.dart:134:10: Context: This is the overridden method ('buildToolbar').
>   Widget buildToolbar(
>          ^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-3.0.0/lib/src/selection/material_text_selection_controls.dart:628:10: Error: The method 'ExtendedMaterialTextSelectionControls.buildToolbar' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildToolbar'.
>   Widget buildToolbar(
>          ^
> ../../../../Apps/flutter/packages/flutter/lib/src/widgets/text_selection.dart:134:10: Context: This is the overridden method ('buildToolbar').
>   Widget buildToolbar(
>          ^
> lib/special_text/my_extended_text_selection_controls.dart:67:59: Error: Too few positional arguments: 2 required, 1 given.
>           handleCopy: canCopy(delegate) ? () => handleCopy(delegate) : null,
>                                                           ^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text-3.0.1/lib/src/selection/extended_text_selection.dart:258:36: Error: Too few positional arguments: 2 required, 1 given.
>         ? () => controls.handleCopy(this)
>                                    ^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-3.0.0/lib/src/selection/cupertino_text_selection_controls.dart:361:70: Error: The argument type 'void Function(TextSelectionDelegate, ClipboardStatusNotifier)' can't be assigned to the parameter type 'void Function(TextSelectionDelegate)'.
>  - 'TextSelectionDelegate' is from 'package:flutter/src/services/text_input.dart' ('../../../../Apps/flutter/packages/flutter/lib/src/services/text_input.dart').
>  - 'ClipboardStatusNotifier' is from 'package:flutter/src/widgets/text_selection.dart' ('../../../../Apps/flutter/packages/flutter/lib/src/widgets/text_selection.dart').
>     addToolbarButtonIfNeeded(localizations.copyButtonLabel, canCopy, handleCopy);
>                                                                      ^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-3.0.0/lib/src/selection/extended_text_selection_overlay.dart:339:46: Error: Too few positional arguments: 7 required, 6 given.
>         child: selectionControls.buildToolbar(
>                                              ^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-3.0.0/lib/src/selection/material_text_selection_controls.dart:671:61: Error: Too few positional arguments: 2 required, 1 given.
>             handleCopy: canCopy(delegate) ? () => handleCopy(delegate) : null,
>                                                             ^
> ../lib/src/extended_editable_text.dart:1740:36: Error: Too few positional arguments: 2 required, 1 given.
>         ? () => controls.handleCopy(this)
>                                    ^
> ../lib/src/extended_editable_text.dart:1850:29: Error: Getter not found: 'obscuringCharacter'.
>       text = RenderEditable.obscuringCharacter * text.length;
>                             ^^^^^^^^^^^^^^^^^^
> lib/special_text/my_extended_text_selection_controls.dart:67:59: Error: Too few positional arguments: 2 required, 1 given.
>           handleCopy: canCopy(delegate) ? () => handleCopy(delegate) : null,
>                                                           ^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text-3.0.1/lib/src/selection/extended_text_selection.dart:258:36: Error: Too few positional arguments: 2 required, 1 given.
>         ? () => controls.handleCopy(this)
>                                    ^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-3.0.0/lib/src/selection/cupertino_text_selection_controls.dart:361:70: Error: The argument type 'void Function(TextSelectionDelegate, ClipboardStatusNotifier)' can't be assigned to the parameter type 'void Function(TextSelectionDelegate)'.
>  - 'TextSelectionDelegate' is from 'package:flutter/src/services/text_input.dart' ('../../../../Apps/flutter/packages/flutter/lib/src/services/text_input.dart').
>  - 'ClipboardStatusNotifier' is from 'package:flutter/src/widgets/text_selection.dart' ('../../../../Apps/flutter/packages/flutter/lib/src/widgets/text_selection.dart').
>     addToolbarButtonIfNeeded(localizations.copyButtonLabel, canCopy, handleCopy);
>                                                                      ^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-3.0.0/lib/src/selection/extended_text_selection_overlay.dart:339:46: Error: Too few positional arguments: 7 required, 6 given.
>         child: selectionControls.buildToolbar(
>                                              ^
> ../../../../Apps/flutter/.pub-cache/hosted/pub.dartlang.org/extended_text_library-3.0.0/lib/src/selection/material_text_selection_controls.dart:671:61: Error: Too few positional arguments: 2 required, 1 given.
>             handleCopy: canCopy(delegate) ? () => handleCopy(delegate) : null,
>                                                             ^
> ../lib/src/extended_editable_text.dart:1740:36: Error: Too few positional arguments: 2 required, 1 given.
>         ? () => controls.handleCopy(this)
>                                    ^
> ../lib/src/extended_editable_text.dart:1850:29: Error: Getter not found: 'obscuringCharacter'.
>       text = RenderEditable.obscuringCharacter * text.length;
>                             ^^^^^^^^^^^^^^^^^^
> Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
> build failed.
> 
> FAILURE: Build failed with an exception.

Master branch - `a8bfcee3056b8b3c64937ea8021e9138b3875f6a` `3.0.1`

`flutter doctor -v`

> [✓] Flutter (Channel master, 1.19.0-2.0.pre, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.19.0-2.0.pre 
>     • Framework revision bb49a9b056 (10 weeks ago), 2020-05-14 12:17:02 -0700
>     • Engine revision ae2222f47e
>     • Dart version 2.9.0 (build 2.9.0-9.0.dev d6fed1f624)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Platform android-29, build-tools 29.0.2
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /snap/android-studio/90/android-studio
>     • Flutter plugin version 45.1.2
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by zmtzawqlp** [comment]
we focus on Flutter Stable Branch , api changes frequently in beta/dev/master
