### ISSUE TITLE
使用TextEditingController设置文字，光标会边到最前面。 

### ISSUE THREAD

**Issue by shaohui93** [fluttercandies/extended_text_field#81]
child: ExtendedTextField(
              specialTextSpanBuilder: _mySpecialTextSpanBuilder,
              controller: _mEtController,
              maxLines: 5,
              focusNode: focusNode1,
              style: TextStyle(color: Colors.black, fontSize: 15),
              decoration: InputDecoration.collapsed(
                  hintText: "在这里，分享我的健康生活…",
                  hintStyle: TextStyle(color: Color(0xff919191), fontSize: 15)),
            )  

//设置新文字
 _mEtController.text = _mEtController.text +
                                "[@" +
                                "mAtUser" +
                                ":" +
                                "11" +
                                "]";
我使用以上代码设置 文字，然后光标会变到最前面，请问一下是否是需要手动设置光标到位置呢？

**Comment by shaohui93** [comment]
版本是   extended_text_field: ^1.0.1

**Comment by zmtzawqlp** [comment]
设置selection

**Comment by shaohui93** [comment]
谢谢，有用
