### ISSUE TITLE
功能加强

### ISSUE THREAD

**Issue by zhanchi88** [fluttercandies/extended_text_field#82]
能加一个禁止点击text_field自动弹出输入法吗？改为手动调用的。
因为在某些情况下输入法顶起布局，然后再刷新布局就会出现一闪的效果

**Comment by zmtzawqlp** [comment]
可以跟官方提一下

**Comment by zhanchi88** [comment]
三方厂也是可以修改的：https://www.jianshu.com/p/4f24d21d46b8?utm_campaign=maleskine

**Comment by zmtzawqlp** [comment]
fork 自己改改？？？

**Comment by zhanchi88** [comment]
能力不足，唉...

**Comment by zmtzawqlp** [comment]
因为在某些情况下输入法顶起布局，然后再刷新布局就会出现一闪的效果

是否是自己代码写的有问题，如果没问题。是否是官方的issue，可以跟官方提供代码，尝试解决
