### ISSUE TITLE
删除bug

### ISSUE THREAD

**Issue by shingohu** [fluttercandies/extended_text_field#83]
版本:4.0.0
平台:iOS
设备:模拟器
本库demo可复现
使用第二个例子(2.text)
输入123 然后@ 然后123 然后 $ 然后123 如下图
![image](https://user-images.githubusercontent.com/4944887/90523232-37c61700-e19f-11ea-9cf7-0a83539287a3.png)
然后先删除最后的123,然后移动到中间的123,删除3,问题出现,3没有被删除$的span变了
![image](https://user-images.githubusercontent.com/4944887/90523375-60e6a780-e19f-11ea-9035-1ea0e8ee9779.png)

**Comment by zmtzawqlp** [comment]
试试最新的版本
