### ISSUE TITLE
Feature Request: Delete detection for special text.

### ISSUE THREAD

**Issue by njovy** [fluttercandies/extended_text_field#85]
I was wondering if I can have a callback upon deleting a special text. For instance, If I have an ```ImageText```, users can delete it by tapping a backspace key but I want to show an alert upon deletion. If the user presses an ok, then delete it otherwise, keep it.

**Comment by zmtzawqlp** [comment]
see demo https://github.com/fluttercandies/extended_text_field/blob/dbbf945f167875ea3919b58bcd0c8970f86ad1bc/example/lib/pages/text_demo.dart#L67
