### ISSUE TITLE
Build failed after upgrading to latest flutter in master channel

### ISSUE THREAD

**Issue by akemimadoka** [fluttercandies/extended_text_field#86]
Error message:

> [ +897 ms] [ +896 ms] /usr/local/Caskroom/flutter/1.20.2/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-4.0.0/lib/src/extended_editable_text.dart:1017:7: Error: The non-abstract class 'ExtendedEditableTextState' is missing implementations for these members:
> [        ] [   +1 ms]  - TextInputClient.performPrivateCommand
> [        ] [        ] Try to either
> [        ] [        ]  - provide an implementation,
> [        ] [        ]  - inherit an implementation from a superclass or mixin,
> [        ] [        ]  - mark the class as abstract, or
> [        ] [        ]  - provide a 'noSuchMethod' implementation.
> [        ] [        ] class ExtendedEditableTextState extends State<ExtendedEditableText>
> [        ] [        ]       ^^^^^^^^^^^^^^^^^^^^^^^^^
> [        ] [        ] /usr/local/Caskroom/flutter/1.20.2/flutter/packages/flutter/lib/src/services/text_input.dart:813:8: Context: 'TextInputClient.performPrivateCommand' is defined here.
> [        ] [        ]   void performPrivateCommand(String action, Map<String, dynamic> data);
> [        ] [        ]        ^^^^^^^^^^^^^^^^^^^^^

This is caused by commit: https://github.com/flutter/flutter/commit/cbe0999d1f211cb29cb9e6fae088a9b700c996d3#diff-87b67489e663f4e6d1894b91a70748deR806, a new method named performPrivateCommand has been introduced.

**Comment by zmtzawqlp** [comment]
don't force on master branch

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_field/issues/87

**Comment by njovy** [comment]
@zmtzawqlp Time to reopen this as 1.22 became stable.

**Comment by zmtzawqlp** [comment]
update later

**Comment by njovy** [comment]
@zmtzawqlp That was super fast. Thank you so much.
