### ISSUE TITLE
Runtime error after upgrading to latest flutter in master channel

### ISSUE THREAD

**Issue by akemimadoka** [fluttercandies/extended_text_field#87]
Error message(some unrelated information was removed):

> ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
> The following _CastError was thrown building Scrollable(axisDirection: down, physics: null, restorationId: null, dirty, dependencies: [_EffectiveTickerMode, _LocalizationsScope-[GlobalKey#8e5ef], _InheritedTheme, ScrollConfiguration], state: ScrollableState#11f24(position: ScrollPositionWithSingleContext#5d2d2(offset: 0.0, range: null..null, viewport: null, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#6144f, ScrollDirection.idle), effective physics: BouncingScrollPhysics -> RangeMaintainingScrollPhysics)):
> Null check operator used on a null value
> 
> The relevant error-causing widget was: 
>   ExtendedTextField-(removed)
> When the exception was thrown, this was the stack: 
> #0      ScrollPosition.minScrollExtent (package:flutter/src/widgets/scroll_position.dart:139:49)
> #1      ExtendedEditableTextState.build.<anonymous closure> (package:extended_text_field/src/extended_editable_text.dart:2125:24)
> #2      ScrollableState.build (package:flutter/src/widgets/scrollable.dart:683:44)
> #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4758:27)
> #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4641:15)
> ...
> ════════════════════════════════════════════════════════════════════════════════════════════════════

This issue is caused by commit https://github.com/flutter/flutter/commit/b007a81ad498eb9b7cd687fda0aa9d8d2bb77dc3#diff-d5d3b3f6ed21039a1a1e9413d814c5eeR139, which introduces non-null assumption on _minScrollExtent and _maxScrollExtent, which may be actually a null value in some situation.

**Comment by zmtzawqlp** [comment]
force on stable branch. master branch is always changing.

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_field/issues/86

force on stable branch. master branch is always changing.
