### ISSUE TITLE
Image Span - Text Selection Error

### ISSUE THREAD

**Issue by brianschardt** [fluttercandies/extended_text_field#95]
When using an ImageSpan the text selection goes to the beginning of the text field. Please help. Big usability issue.

![Screen Shot 2020-10-23 at 9 01 08 AM](https://user-images.githubusercontent.com/35744893/97026606-73b68900-150e-11eb-815b-13a22e1375f3.png)

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_field/issues/31

**Comment by zmtzawqlp** [comment]
know issue on some flutter sdk version
