### ISSUE TITLE
How to  - Add meta data to special text.

### ISSUE THREAD

**Issue by brianschardt** [fluttercandies/extended_text_field#96]
We are looking to add meta data to special text e.g.

@[USER]:1728:Brian Schardt

Display String= @BrianSchardt 
When clicked it will route the the user profile page /user/1728

We are trying to add functionality that will allow the user to be able to take some action based on more than just the information shown.

**Comment by zmtzawqlp** [comment]
start @[USER]  end with space ， show as @brianschardt , and click get actual text

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_text_field/blob/master/example/lib/special_text/at_text.dart

**Comment by brianschardt** [comment]
Where would you store the userId in the string so you can route to the user page?

**Comment by zmtzawqlp** [comment]
at_text.dart  you can stroe it in any way, i didn't get you

**Comment by brianschardt** [comment]
Example,

IF we have a string = 
```
Have you seen the basketball game @[USER:3423]scottthomas ? it was great!!
```
and you want it to look like
```
Have you seen the basketball game **@scottthomas** ? it was great!!
```
And if you click the bolded name it will route you to /user/3423
the userId in the original string

**Comment by AlexV525** [comment]
See https://github.com/openjmu/OpenJMU/blob/master/lib/model/special_text.dart#L86 . Thanks.

**Comment by brianschardt** [comment]
@AlexV525 how do you implement this in the extended text field tho?

**Comment by AlexV525** [comment]
Idk what kind of implement is your desire, but I did almost the same thing as demo.
