### ISSUE TITLE
大佬求个功能

### ISSUE THREAD

**Issue by suyie001** [fluttercandies/extended_text_field#97]
我需要改变一下文字的换行方向，正常来说 写满一行或者按回车后 新的一行是出现在文字的下面的。但我想要新的一行出现在原有段落的上面，每一行都是往上换行。

**Comment by zmtzawqlp** [comment]
自己 tranform 一下？？

**Comment by suyie001** [comment]
> 自己 tranform 一下？？

transform的话 字也会倒过来，显然不是我想要的额。可以有偿解决 这个需求吗？比如

**Comment by suyie001** [comment]
比如：‘123456789’，
正常的textfield里换行的话是这样：
‘12345’
‘6789’。
我想要的是：
‘6789’
‘12345’。
换行的方向不一样

**Comment by zmtzawqlp** [comment]
群里问问其他人有办法没有
